### PR TITLE
COMP: Fix unit tests for OpenCV 4

### LINKED ISSUE #806: BridgeOpenCV fails to build with OpenCV 4
### Description

For example, when building unit tests:

```
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe 
... .../ITK\Modules\Video\BridgeOpenCV\test\itkOpenCVImageBridgeGrayScaleTest.cxx
.../opencv2/imgcodecs/imgcodecs_c.h(1): fatal error C1189: #error:  "This header with legacy C API declarations has been removed from OpenCV. Legacy contants are available from legacy/constants_c.h file." 
```

### Steps to Reproduce

1. Build ITK against OpenCV4 4.0.1 with `-DBUILD_TESTING:BOOL=ON -DModule_ITKVideoBridgeOpenCV:BOOL=ON`

### Versions

Latest master (b83454ef2b4d2385adddab67d6378fe8c47f8800)

### Environment

Tested on Windows with MSVC 2015 and 2017 and Ubuntu 18.04 gcc-6

### PR DESCRIPTION
**Pull request by nocnokneo**
Fixes #806

## PR Checklist

- :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] Adds the License notice to new files.
- :no_entry_sign: Adds Python wrapping.
- :no_entry_sign: Adds tests and baseline comparison (quantitative).
- :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- :no_entry_sign: Adds Documentation.

### CODE REVIEW

File: Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.cxx [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+#if CV_VERSION_MAJOR > 3
+// Based on https://stackoverflow.com/a/13683381/471839
+IplImage *
+cvLoadImage(const char * filename, int iscolor)
+{
+  std::map<int, int> matDepthToIplDepth{ { CV_8U, IPL_DEPTH_8U },   { CV_8S, IPL_DEPTH_8S },
+                                         { CV_16U, IPL_DEPTH_16U }, { CV_16S, IPL_DEPTH_16S },
+                                         { CV_32S, IPL_DEPTH_32S }, { CV_32F, IPL_DEPTH_32F },
+                                         { CV_64F, IPL_DEPTH_64F } };
```
Comment (nocnokneo) [inline Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.cxx]: FYI - I had to bypass the pre-commit hooks to avoid:
```
Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.cxx:40: error: Unnecessary semicolon
pre-commit hook failure
-----------------------

KWStyle check failed.
```
