### PR TITLE
BUG: Adds RemovePoint() to PointBasedSpatialObjects

### LINKED ISSUE #692: RemovePoint() needed in PointBasedSpatialObjects
During ITKv5 refactoring, `RemovePoint( IdentifierType id )` was removed.  It should be restored to the `PointBasedSpatialObject` class

### PR DESCRIPTION
**Pull request by aylward**
This PR resolves #692 by adding the `RemovePoint( IdentifierType id )` function to `PointBasedSpatialObjects`.   Also adds tests to the `TubeSpatialObjectTest.cxx` file.

### CODE REVIEW

File: Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h [hunk 1]
```diff
@@ -66,6 +66,10 @@ class ITK_TEMPLATE_EXPORT PointBasedSpatialObject:
    * each point (for computing world coordinates) */
   virtual void AddPoint( const SpatialObjectPointType & newPoints );
 
+  /** Assign points to this object, and assigned this object to
```
Comment (dzenanz) [inline Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h]: Documentation wrong. Copy-pasted but not modified?

Comment (aylward) [reply Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h]: Thanks!  Fixed!
