### PR TITLE
BUG: Fix number encoding to use C locale

### LINKED ISSUE #2067: MacOS itk vtk glue
### Description

I have a segmentation pipeline relying on itk 4.13 and vtk 8.1 . It is supposed to load a *.vtk structured points file. Somehow I get errors of "Determinant must not be 0" or "slice spacing is zero". 
The header of the vtk volume producing the outcome:
```
# vtk DataFile Version 3.0
VTK File Generated by Insight Segmentation and Registration Toolkit (ITK)
BINARY
DATASET STRUCTURED_POINTS
DIMENSIONS 369 369 160 
SPACING 1.0000000000000000e+00 1.0000000000000000e+00 2.5000000000000000e+00 
ORIGIN -1.9830000305175781e+02 -1.8500000000000000e+02 -4.0750000000000000e+02 
POINT_DATA 21785760
SCALARS scalars short 1
LOOKUP_TABLE default

```

After doing further investigation I noticed that the ITKVtkglue tests fail on my machine:
```
Total Test time (real) = 404.70 sec

The following tests FAILED:
	1296 - itkCastImageFilterTest (Failed)
	2539 - itkVtkMedianImageFilterTest (SEGFAULT)
	2543 - QuickViewTest (SEGFAULT)
	2544 - itkVtkConnectedComponentImageFilterTest (Failed)
[ERROR_MESSAGE] 
Errors while running CTest
```
I am thinking that it might be connected.
### Steps to Reproduce

**Reproduce reading**
```cpp
      typedef itk::Image<short, 3> ImageType;
      typedef itk::ImageFileReader<ImageType> ImageFileReaderType;
      ImageFileReaderType::Pointer reader = ImageFileReaderType::New();
      try {
         reader->SetFileName(imageDataPath);
         reader->Update();
      } catch (itk::ExceptionObject &err) {
         std::cerr << err << std::endl;
      }
```
**Reproduce test outcome**
1. Build Vtk 8.1
```
cmake .. \
      -DCMAKE_CXX_STANDARD=11 \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
      -DVTK_LEGACY_REMOVE=ON \
      -DCMAKE_MACOSX_RPATH=ON \
      -DCMAKE_INSTALL_RPATH=\$ORIGIN \
      -DBUILD_TESTING=OFF \
      -DBUILD_EXAMPLES=OFF \
      -DModule_vtkRenderingExternal=ON
cmake --build . -j`nproc`
```
2. Build itk 4.13-release
```
cmake .. \
      -DVTK_DIR=${VTK_DIR} \
      -DCMAKE_CXX_STANDARD=11 \
      -DCMAKE_CXX_EXTENSIONS=OFF \
      -DCMAKE_CXX_STANDARD_REQUIRED=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
      -DITK_LEGACY_REMOVE=ON \
      -DCMAKE_INSTALL_RPATH=\$ORIGIN \
      -DModule_ITKVtkGlue=ON \
      -DModule_IOSTL=ON \
      -DModule_LesionSizingToolkit=ON \
      -DBUILD_TESTING=ON \
      -DBUILD_EXAMPLES=OFF \
      -DITK_SKIP_PATH_LENGTH_CHECKS=ON 
cmake --build . -j`nproc`
```
3. Run tests

### Expected behavior

Tests to complete without errors

### Actual behavior

**itkVtkConnectedComponentImageFilterTest**
```none
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff796376f2 libsystem_platform.dylib`_platform_strlen + 18
    frame #1: 0x000000010e5393a5 ITKVtkGlueTestDriver`std::__1::char_traits<char>::length(__s=0x0000000000000000) at __string:218:53
    frame #2: 0x000000010e523f9c ITKVtkGlueTestDriver`std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<std::__1::char_traits<char> >(__os=0x00007fffaf1a1770, __str=0x0000000000000000) at ostream:865:57
    frame #3: 0x000000010e71f93e ITKVtkGlueTestDriver`itkVtkConnectedComponentImageFilterTest(argc=0, argv=0x00007ffee16f0a98) at itkVtkConnectedComponentImageFilterTest.cxx:45:28
    frame #4: 0x000000010e5333df ITKVtkGlueTestDriver`main(ac=0, av=0x00007ffee16f0a98) at ITKVtkGlueTestDriver.cxx:162:14
    frame #5: 0x00007fff7944f3d5 libdyld.dylib`start + 1

```
Tests fail or segfault

### Reproducibility

100%

### Versions

4.13.3

### Environment

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G5033
```
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 
```
cmake version 3.17.3
```

### PR DESCRIPTION
**Pull request by okaerin**
The floating point number encoding defaults to the C locale on the standard C++ std IO. The sscanf uses the OS dependent LC_NUMERIC value. This fixes that behavior
**EDIT**
Closes #2067

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

File: Modules/IO/GDCM/src/itkGDCMImageIO.cxx [hunk 1]
```diff
@@ -1022,7 +1022,9 @@ GDCMImageIO::Write(const void * buffer)
   if (hasIPP)
   {
     double origin3D[3];
+    std::locale currentLocale = std::locale::global(std::locale::classic());//save and reset old locale
```
Comment (dzenanz) [inline Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1025]:
```suggestion
    std::locale currentLocale = std::locale::global(std::locale::classic()); // save and reset old locale
```

**Review by dzenanz — COMMENTED** [review]
Code looks good. Minor style issue: there should be a space between statement and a comment. The in-line suggestion should be applied to all the cases.

File: Modules/IO/GDCM/src/itkGDCMImageIO.cxx (hunk 1 above)
Comment (okaerin) [reply Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1025]: I would like to commit your suggestions, but the pre commit hook does not let me do it. Got any tip to apply?
```
[attr]our-c-style  whitespace=tab-in-indent,no-lf-at-eof  hooks.style=KWStyle,clangformat
 not allowed: ./.gitattributes:31
[attr]our-c-style  whitespace=tab-in-indent,no-lf-at-eof  hooks.style=KWStyle,clangformat
 not allowed: ./.gitattributes:31
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:69: error: Unnecessary semicolon
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:156: error: Unnecessary semicolon
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:245: error: Unnecessary semicolon
pre-commit hook failure
-----------------------

KWStyle check failed.

Line numbers in the errors shown refer to the file:
Modules/IO/GDCM/src/itkGDCMImageIO.cxx.kws

```

Comment (thewtex) [reply Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1025]: We could put the comment above the code line.

File: Modules/IO/VTK/src/itkVTKImageIO.cxx [hunk 2]
```diff
@@ -247,6 +249,7 @@ VTKImageIO::InternalReadImageInformation(std::ifstream & file)
     else if (text.find("origin") < text.length())
     {
       double origin[3];
+      std::locale currentLocale = std::locale::global(std::locale::classic());//save and reset old locale
       sscanf(text.c_str(), "%*s %lf %lf %lf", origin, origin + 1, origin + 2);
       for (unsigned int i = 0; i < m_NumberOfDimensions; i++)
```
Comment (malaterre) [inline Modules/IO/VTK/src/itkVTKImageIO.cxx:254]: why not reset here ?

Comment (okaerin) [reply Modules/IO/VTK/src/itkVTKImageIO.cxx:254]: Seems like I forgot to do it there. I'll add id into another commit.

File: Modules/IO/GDCM/src/itkGDCMImageIO.cxx (hunk 1 above)
Comment (okaerin) [reply Modules/IO/GDCM/src/itkGDCMImageIO.cxx]: I couldn't commit because of KWStyle throwing an bogus error on a line I did not modify. Seems to be somewhat related to this discussion [https://discourse.itk.org/t/help-with-bogus-pre-commit-hook-failure/2350/7](https://discourse.itk.org/t/help-with-bogus-pre-commit-hook-failure/2350/7) . Though I made sure that I had a fresh build with the KWStyle binary in place. I had to disable kwstyle checking...

**Review by dzenanz — APPROVED** [review]
