### PR TITLE
BUG: avoid undefined behavior (dereferencing nullptr). Closes #1358

### LINKED ISSUE #1358: null deref in 'itkTreeContainerTest' found by UBSan
itkTreeContainerTest fails under UBSan on my dashboards, ex:

https://open.cdash.org/testDetails.php?test=799482596&build=6175118

```
/Users/builder/external/ITK/Modules/Core/Common/include/itkChildTreeIterator.hxx:112:28: runtime error: member call on null pointer of type 'itk::TreeNode<int>'
```

in the debugger:

```
frame #4: 0x0000000100140292 ITKCommon2TestDriver`itk::ChildTreeIterator<itk::TreeContainer<int> >::Next(this=<unavailable>) at itkChildTreeIterator.hxx:112:28 [opt]
   109 	{
   110 	  m_ListPosition++;
   111 	  this->m_Position = m_ParentNode->GetChild(m_ListPosition);
-> 112 	  return this->m_Position->Get();
   113 	}
   114 	
   115 	/** Clone function */
```

@dzenanz I thought you fixed this last year, but maybe this is another variation:

https://discourse.itk.org/t/help-with-null-deref-in-itktreecontainertest/826/1

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
Look reasonable to me, but I don't know this code really.

File: Modules/Core/Common/include/itkLeafTreeIterator.h [hunk 1]
```diff
@@ -134,6 +134,10 @@ const typename LeafTreeIterator<TTreeType>::ValueType &
 LeafTreeIterator<TTreeType>::Next()
 {
   this->m_Position = const_cast<TreeNodeType *>(FindNextNode());
+  if (this->m_Position == nullptr)
+  {
+    return this->m_Root->Get(); // value irrelevant, but we have to return something
```
Comment (N-Dekker) [inline Modules/Core/Common/include/itkLeafTreeIterator.h]: Sorry, I'm not familiar with this class. Is it still being used? If so, could a user application actually get at this line of code, during program execution? Should it get an assert failure here?

Comment (seanm) [reply Modules/Core/Common/include/itkLeafTreeIterator.h]: A test gets there: https://open.cdash.org/testDetails.php?test=817215405&build=6229026

Comment (dzenanz) [reply Modules/Core/Common/include/itkLeafTreeIterator.h]: I am not familiar with this class either, and I don't know if it is being used.

The unit test gets to here, but the result is commonly discarded, so the whole operation is commonly optimized away. But as Sean's tool notes, it is undefined behavior.

Comment (seanm) [reply Modules/Core/Common/include/itkLeafTreeIterator.h]: The tool in question is -fsanitize=null https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html

Comment (N-Dekker) [reply Modules/Core/Common/include/itkLeafTreeIterator.h]: If the return value is commonly ignored, maybe just make it `void`. Otherwise I think an assert failure might be helpful. But again, I don't really know.

Comment (dzenanz) [reply Modules/Core/Common/include/itkLeafTreeIterator.h]: `operator++` (iterator increment) returns this reference, which is common in C++, but the [usual use pattern](https://github.com/InsightSoftwareConsortium/ITK/blob/2074c2f9e5ed3f087d0e2059f8e0e8992fcad7ef/Modules/Core/Common/test/itkTreeContainerTest.cxx#L160-L167) does not use that reference. And since this group of classes seems to be used rarely (if at all), refactoring them is not a priority.

**Comment by dzenanz** [comment]
Windows Python packages timed out.

**Comment by seanm** [comment]
@dzenanz there are still 2 more null deref related treecontainer failures:

Test: itkTreeContainerTest and itkTreeContainerTest2
https://open.cdash.org/viewTest.php?onlyfailed&buildid=6239707
