### PR TITLE
COMP: GaussianInterpolateImageFunction test narrowing

### LINKED ISSUE #766: ITK build failed due to error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion with MSVC on windows
ITK build failed due to error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion with MSVC on windows. It can be reproduced on master version 651ee50 and this issue can be first reproduced on master version b9f39dd.It should be an ITK source issue. Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:
 1.git clone http://itk.org/ITK.git D:\ITK\src
 2.open VS2017 x86 command prompt as admin and browse to D:\ITK
 3.set CL=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %CL%
 4.mkdir build_x86 && pushd build_x86
 5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..\src
 6.msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

The whole log file please see attachment.
[log_x86_build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3115886/log_x86_build.log)

Acutal result:
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion 
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397:       image->SetPixel({{i, j}}, i + j);

### PR DESCRIPTION
**Pull request by thewtex**
To address:

  D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion
  D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: image->SetPixel({{i, j}}, i + j);

Closes #766

### CODE REVIEW

File: Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx [hunk 1]
```diff
@@ -65,13 +65,13 @@ int itkGaussianInterpolateImageFunctionTest( int, char*[] )
...
-  for ( unsigned int i = 0; i < 3; ++i )
-  {
-    for ( unsigned int j = 0; j < 3; ++j )
+  for ( itk::IndexValueType i = 0; i < 3; ++i )
     {
+    for ( itk::IndexValueType j = 0; j < 3; ++j )
+      {
       image->SetPixel({{i, j}}, i + j);
+      }
     }
```
Comment (N-Dekker) [inline Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx]: Looks like you could do it with a single range-based for-loop, instead of two old-style for-loops:

      using itk::Experimental::ZeroBasedIndexRange;

      for (const auto index : ZeroBasedIndexRange<ImageType::ImageDimension>(size))
      {
        image->SetPixel(index, index[0] + index[1]);
      }

But well... I approved your fix already  `:-)`

Comment (thewtex) [reply Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx]: Beeeeeautiful, @N-Dekker -- adding! :-)
