### PR TITLE
BUG: DCMTK reader wrongly rejects file with preamble

### LINKED ISSUE #4108: DCMTK reader fails for valid files
### Description

Valid dicom files are rejected.

### Steps to Reproduce

Use the itkDCMTKImageIO to read a file that has a dicom preamble and it is incorrectly rejected.

### Expected behavior

File should be accepted.

### Actual behavior

The `readNoPreambleDicom` implements a heuristic to see if the file starts with valid group/element tags.

https://github.com/InsightSoftwareConsortium/ITK/blame/master/Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx#L231

But it fails when there is a preamble (which is often the case) there are 128 bytes and then the letters DICM.

https://dicom.nema.org/medical/dicom/current/output/html/part10.html#chapter_7

### Reproducibility

Always

### Versions

It appears to have been introduced by this commit:

https://github.com/InsightSoftwareConsortium/ITK/commit/19fa58feb02bfd45154e811d0e13510787e2adfb

### Environment

All platforms.

### Additional Information

I have a fix and will submit a PR.

### PR DESCRIPTION
**Pull request by thewtex**
A previous optimization didn't take into account the preamble of a dicom file.  This adds a check.

Fixes #4108

### CODE REVIEW

File: Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx [hunk 1]
```diff
@@ -31,6 +31,26 @@
...
+ * Helper function to test for 128 byte dicom preamble
+ * @param file A stream to test if the file is dicom like
+ * @return true if the stream has a dicom preamble
+ */
+static bool
+readPreambleDicom(std::ifstream & file) // NOTE: This file is duplicated in itkGDCMImageIO.cxx
+{
+  unsigned char preamble[132];
+
+  file.read(reinterpret_cast<char *>(preamble), 132);
```
Comment (N-Dekker) [inline Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx:47]: Please consider, instead:

```cpp
    char preamble[132] = "";

    file.read(preamble, sizeof(preample));
```
- properly initializing `preamble` to avoid undefined behavior in the `return` statement (especially in the case when `file.read` has silently failed).
- avoiding unnecessary `reinterpret_cast<char *>`
- avoiding typing the same magic number `132` twice.

File: Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx [hunk 2]
```diff
@@ -276,7 +300,7 @@ DCMTKImageIO::Read(void * buffer)
   this->OpenDicomImage();
   if (m_DImage->getStatus() != EIS_Normal)
   {
-    itkExceptionMacro("Error: cannot load DICOM image (" << DicomImage::getString(m_DImage->getStatus()) << ')');
+    itkExceptionMacro("Error: cannot load DICOM image (" << DicomImage::getString(m_DImage->getStatus()) << ")");
```
Comment (N-Dekker) [inline Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx:303]: Thanks, but why would you not leave the single-quotes there, with `')'`?

**Comment by thewtex** [comment]
Great suggestions, @N-Dekker , added.

**Comment by N-Dekker** [comment]
> Fixes #4801

Are you sure it's issue 4801? I cannot find it  🤷

**Review by jhlegarreta — COMMENTED** [review]
Can a minimal test be added if an appropriate dataset can be found, please?

**Comment by thewtex** [comment]
@pieper do you have a test file?

**Comment by issakomi** [comment]
> Can a minimal test be added if an appropriate dataset can be found, please?

Almost every DICOM file has the "preamble". There are old ACR-NEMA files without preamble / prefix / header (0x0002 group).
Strictly speaking, the _preamble_ consists of 128 zero bytes at the beginning (reserved), and the subsequent 4 bytes "DICM" are called the _prefix_.
https://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html

Here is one _without_ preamble and prefix, starts with header (0x0002 group), specially for testing purposes. Most DICOM viewers open it. It is also 'dciodvfy` clean.
https://data.kitware.com/#item/65efb22b8353a45974ec3998

**Comment by issakomi** [comment]
> > Fixes #4801
> 
> Are you sure it's issue 4801? I cannot find it 🤷

https://github.com/InsightSoftwareConsortium/ITK/issues/4108

**Comment by thewtex** [comment]
@issakomi awesome, thank you!  I added tests accordingly for both GDCM, DCMTK.

**Review by jhlegarreta — APPROVED** [review]

**Comment by issakomi** [comment]
Please give me some time for more test. I am not sure that we have tested CanReadFile. It seems to reject no_preamble.dcm. The name of the PR is a little bit not precise. The DCMTK reader don't reject files with preamble. CanReadFile return _false_, but it is usually not invoked at all, only if a user calls it explicitly. So the reader works work with files with preamble (almost all test files). For ACR-NEMA files (without preamble) ... CanReadFile returns _true_, but the DCMTK reader fails.

**Comment by issakomi** [comment]
Here is [test](https://data.kitware.com/api/v1/item/65f170c68353a45974ec3a85/download) with CanReadFile and readers for both DCMTKIO and GDCMIO.

-------------------------------------------------------------------------------------------
```
r@deb2:~/tmp/test11/build$ ./test ../data/preamble.dcm 

DCMTKIO CanReadFile(../data/preamble.dcm): false

GDCMIO CanReadFile(../data/preamble.dcm): true
```
Failure for DCMTK _CanReadFile_ with preamble will be fixed by this PR

-------------------------------------------------------------------------------------------

```
r@deb2:~/tmp/test11/build$ ./test ../data/no_preamble.dcm 

DCMTKIO CanReadFile(../data/no_preamble.dcm): false

GDCMIO CanReadFile(../data/no_preamble.dcm): false
```

Not sure that it is important, no_preamble.dcm is synthetic, but both readers work with it. 

-------------------------------------------------------------------------------------------

```
r@deb2:~/tmp/test11/build$ ./test ../data/SIEMENS_GBS_III-16-ACR_NEMA_1.acr 
No DICOM magic number found, but the file appears to be DICOM without a preamble.
Proceeding without caution.
DCMTKIO CanReadFile(../data/SIEMENS_GBS_III-16-ACR_NEMA_1.acr): false
DCMTKIO reader failed
ITK ERROR: DCMTKImageIO(0x564451eb2bf0): Missing Image Data in ../data/SIEMENS_GBS_III-16-ACR_NEMA_1.acr
No DICOM magic number found, but the file appears to be DICOM without a preamble.
Proceeding without caution.
GDCMIO CanReadFile(../data/SIEMENS_GBS_III-16-ACR_NEMA_1.acr): true
```

SIEMENS_GBS_III-16-ACR_NEMA_1.acr is real ACR-NEMA file, DCMTKIO reader fails.

-------------------------------------------------------------------------------------------



```cpp
#include "itkImage.h"
#include "itkDCMTKImageIO.h"
#include "itkGDCMImageIO.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include <iostream>

int main(int argc, char ** argv)
{
  if (argc < 2)
  {
    std::cout << "Filename is required" << std::endl;
  }
  {
    using ImageType = itk::Image<unsigned char, 2>;
    using ImageIOType = itk::DCMTKImageIO;
    auto io = ImageIOType::New();

    ////////////////////////////////////////////////////////////////////////
    //
    // Bug https://github.com/InsightSoftwareConsortium/ITK/issues/4108
    //
    try
    {
      const bool r = io->CanReadFile(argv[1]);
      std::cout << "\nDCMTKIO CanReadFile(" << argv[1] << "): " << (r ? "true" : "false") << std::endl;
    }
    catch (const itk::ExceptionObject & e)
    {
      std::cout << e.GetDescription() << std::endl;
    }
    //
    //
    ////////////////////////////////////////////////////////////////////////

    itk::ImageFileReader<ImageType>::Pointer reader = itk::ImageFileReader<ImageType>::New();
    reader->SetImageIO(io);
    reader->SetFileName(argv[1]);
    try
    {
      reader->Update();
    }
    catch (const itk::ExceptionObject & e)
    {
      std::cout << "DCMTKIO reader failed\n" << e.GetDescription() << std::endl;
    }
  }
  //
  {
    using ImageType = itk::Image<unsigned char, 2>;
    using ImageIOType = itk::GDCMImageIO;
    auto io = ImageIOType::New();

    ////////////////////////////////////////////////////////////////////////
    //
    //
    try
    {
      const bool r = io->CanReadFile(argv[1]);
      std::cout << "\nGDCMIO CanReadFile(" << argv[1] << "): " << (r ? "true" : "false") << std::endl;
    }
    catch (const itk::ExceptionObject & e)
    {
      std::cout << e.GetDescription() << std::endl;
    }
    //
    //
    ////////////////////////////////////////////////////////////////////////

    itk::ImageFileReader<ImageType>::Pointer reader = itk::ImageFileReader<ImageType>::New();
    reader->SetImageIO(io);
    reader->SetFileName(argv[1]);
    try
    {
      reader->Update();
    }
    catch (const itk::ExceptionObject & e)
    {
      std::cout << "GDCMIO reader failed\n" << e.GetDescription() << std::endl;
    }
  }
  return 0;
}
```

**Review by issakomi — APPROVED** [review]
Approved for clarity. Despite of issues reported above, the PR is a step in the right direction.

**Comment by thewtex** [comment]
@issakomi thank you for helping us progress forward in the right direction on this!!

I added a few more tests that improve our coverage based on your remarks.
