### PR TITLE
BUG: Fix infinite loop in VoronoiDiagram2DGenerator

### LINKED ISSUE #4386: Deadlock in `itk::VoronoiDiagram2DGenerator<double>::ConstructDiagram()`
### Description

This simple example with these specific values deadlocks.

### Steps to Reproduce

```
#include <itkVoronoiDiagram2DGenerator.h>

int main()
{
    using VoronoiDiagramType         = itk::VoronoiDiagram2D<double>;
    using VoronoiGeneratorType       = itk::VoronoiDiagram2DGenerator<double>;
    using PointType                  = VoronoiDiagramType::PointType;
    VoronoiGeneratorType::Pointer vg = VoronoiGeneratorType::New();
    vg->SetOrigin(PointType {{-1.61569, -1.76726}});
    vg->SetBoundary(PointType {{1.60174, 1.76345}});
    vg->AddOneSeed(PointType {{-1.39649, 0.322212}});
    vg->AddOneSeed(PointType {{-1.30128, 0.231786}});
    vg->AddOneSeed(PointType {{-1.21509, 0.0515039}});
    vg->AddOneSeed(PointType {{-1.22364, -0.030281}});
    vg->AddOneSeed(PointType {{-1.22125, -0.120815}});
    vg->AddOneSeed(PointType {{-1.25159, -0.23593}});
    vg->Update();
}
```

### Expected behavior

No deadlock.

### Actual behavior

Deadlock.

### Reproducibility

Every time.

### Versions

ITK 5.1.2; reproducing on a recent version would be possible but very painful, as I'm in a restricted work environment.

### Environment

Tested on MacOS Ventura (Apple clang 15) and Windows 11 (MSVC 2019).

### PR DESCRIPTION
**Pull request by hjmjohnson**
## Summary

Fix an infinite loop in `VoronoiDiagram2DGenerator::ConstructDiagram()` that
occurs with certain degenerate seed configurations (ITK issue #4386).

Supersedes PR #5400 by @ILoveGoulash with an improved termination strategy
that preserves correctness for all existing tests.

## Root Cause

`ConstructDiagram()` builds Voronoi cell boundaries by assembling raw edges
into a connected chain. It pops an edge from the deque, tries to attach it
to the front or back of the growing chain, and pushes it back if it cannot
attach. With certain seed configurations, some edges can never be attached
(due to the geometric structure of the Voronoi diagram near boundary
corners), causing the loop to cycle endlessly.

The loop exit condition (`maxStop`) was originally present but was never
wired into the `while` condition. Commit cd97879e (2023) removed it as an
"unused variable."

## Why PR #5400's fix was insufficient

PR #5400 restored `maxStop` as a simple countdown (`maxStop = rawEdges[i].size()`,
decrement each iteration). This limits the loop to one pass through the deque,
but is **too aggressive**: when an edge successfully attaches, it changes the
chain's front/back endpoints, potentially making previously unattachable edges
now attachable. The simple countdown drops these edges prematurely.

**Evidence**: With PR #5400's approach, `itkVoronoiPartitioningImageFilterTest2`
fails (17 pixels differ, mean error 29.1) because edges that would have been
attachable in a subsequent pass were dropped.

## This fix

This PR uses a **stall-detection** strategy instead of a simple countdown:

```cpp
auto remainingBeforeStall = rawEdges[i].size();
while (!(rawEdges[i].empty()) && (remainingBeforeStall != 0))
{
  --remainingBeforeStall;
  // ... try to attach edge ...
  bool edgeAttached = /* true if any branch consumed the edge */;
  if (edgeAttached)
  {
    // Progress was made — previously unattachable edges may now fit.
    remainingBeforeStall = rawEdges[i].size();
  }
}
```

The counter resets whenever an edge attaches. The loop only terminates when
a **full pass** through the remaining edges makes **zero progress** — proving
that no further edges can ever attach. This is both correct (preserves the
algorithm's ability to attach edges in multiple passes) and safe (guaranteed
O(n^2) termination in the worst case).

## Test Results

| Test | PR #5400 | This PR |
|------|----------|---------|
| `itkVoronoiDiagram2DInfiniteLoopTest` | Pass | Pass |
| `itkVoronoiSegmentationImageFilterTest` | Pass | Pass |
| `itkVoronoiSegmentationRGBImageFilterTest` | Pass | Pass |
| `itkVoronoiDiagram2DTest` | Pass | Pass |
| `itkVoronoiPartitioningImageFilterTest1` | Pass | Pass |
| `itkVoronoiPartitioningImageFilterTest2` | **Fail** (17 px) | **Pass** |

**8/8 Voronoi tests pass** with this fix.

## AI Assistance

Claude Code (Opus) was used to:
- Analyze the algorithm and identify the root cause of the infinite loop
- Identify the flaw in PR #5400's simple-countdown approach
- Implement the stall-detection fix and verify it against all existing tests
- Write the regression test and this PR description

All analysis and changes were reviewed and validated by the commit author.

## Testing

```bash
cmake --build cmake-build-Release --target ITKVoronoiTestDriver -j$(nproc)
cd cmake-build-Release && ctest -R Voronoi --output-on-failure
# 100% tests passed, 0 tests failed out of 8
```

Closes #4386.

### CODE REVIEW

File: Modules/Segmentation/Voronoi/test/itkVoronoiDiagram2DInfiniteLoopTest.cxx [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+ *  limitations under the License.
+ *
+ *=========================================================================*/
+
+#include "itkVoronoiDiagram2DGenerator.h"
+#include "itkTestingMacros.h"
+
+// Regression test for ITK issue #4386: certain seed configurations
+// caused an infinite loop in VoronoiDiagram2DGenerator::ConstructDiagram()
+// because unattachable edges were endlessly recycled in the deque.
```
Comment (hjmjohnson) [inline Modules/Segmentation/Voronoi/test/itkVoronoiDiagram2DInfiniteLoopTest.cxx]: Perhaps we should be more verbose in describing the exact scenerio where unattachable edges were endlessly recycled in the deque.

What is the condition that arises that makes an edge unattachable?  Is is a case were two edges produce identical (floating point equality) where either edge is ok to process and produces the exact same result regardless of queue order processing, or is it some other case that should be handled differently?

====
This may be too much information for a comment here.

Comment (hjmjohnson) [reply Modules/Segmentation/Voronoi/test/itkVoronoiDiagram2DInfiniteLoopTest.cxx]: I have a concern that this fixes the current 2 problems 1) backward compatible for most datasets, and 2) no infinite loop hang (but perhaps not the correct answer).  I think the unattached edges that cant be processed need a better explanation of why they are unattached.  Is it that they can not be processed because another point has already occupied that output space and the current unattached edge would simply write the same answer to the already occupied output space, or is it that a different answer would occupy the output space that is conceptually just as valid, but a different value, or that the output space should be some combination of the various results that are requested to be written to that space?

**Review by dzenanz — APPROVED** [review]
Looks good on a glance. It would be good if somebody else reviewed too.

**Comment by hjmjohnson** [comment]
## Investigation Report: Unattachable Edges in VoronoiDiagram2DGenerator

### Experiment Setup

Added diagnostic instrumentation to `ConstructDiagram()` to log:
- Which cells drop edges, how many, and their coordinates
- The chain state (front/back vertex) at time of stall
- Boundary classification (`Pointonbnd`) of all involved vertices
- Full cell boundary polygons for all 6 cells

Ran all 8 Voronoi tests with instrumentation.

### Key Finding: Only 1 Edge Dropped, Only in the Degenerate Case

**All existing Voronoi tests (normal seed configurations) produce zero dropped edges.** Only the degenerate infinite-loop test (issue #4386) drops a single edge in cell 2.

### The Dropped Edge — Detailed Analysis

```
Cell 2: 1 unattachable edge dropped
  Chain: front=back=vertex 0 (-1.58976, -0.0852448)  [single-vertex closed loop]
  Dropped: vertex 5 (-1.61569, -0.0039021) → vertex 2 (-1.61566, -0.00388532)
           Both endpoints on boundary 1 (left wall: x = -1.61569)
           Chain endpoints NOT on boundary (frontbnd=0, backbnd=0)
```

**What happened:** The chain for cell 2 assembled into a closed loop (front == back == vertex 0) *before* this edge was processed. The edge connects two points on the left boundary wall that are extremely close together (Δx = 0.00003, Δy = 0.00002). Neither endpoint matches the chain's single vertex, and the boundary-matching logic doesn't apply because the chain endpoints are not on a boundary.

### Why This Edge is Unattachable

The edge `5→2` is unattachable because:

1. **The chain is already closed** — `front[0] == back[1] == vertex 0`. There is no open end to attach to.
2. **No endpoint match** — Neither vertex 5 nor vertex 2 equals vertex 0 (direct attach fails).
3. **No boundary bridging** — The chain endpoints are interior (not on domain boundary), so the boundary-matching branches (`frontbnd != 0 || backbnd != 0`) don't fire.

### Is the Edge Redundant?

Looking at the final cell boundaries:

```
Cell 2: [0]→[4]→[2]→[1]→[6]  (5 vertices, includes vertex 2)
Cell 5: [7]→[12]→[5]→[2]      (4 vertices, includes both vertex 5 and 2)
```

**Vertex 2 is already in cell 2's boundary** (attached via a different path). **Vertex 5 is in cell 5's boundary.** The dropped edge `5→2` would represent a shared boundary segment between cells 5 and 2, which is already represented by the vertex 2 being shared between both cells. The edge is topologically redundant — it describes a boundary segment that both cells already incorporate through their other edges.

### Is the Result Geometrically Correct?

The 6 seeds near-collinear along x ≈ -1.2 to -1.4 create Voronoi cells that are extremely elongated. The two vertices `5` and `2` on the left boundary are only 0.00003 apart — this is a near-degenerate edge from Fortune's algorithm. In exact arithmetic, this edge likely has zero length (the two boundary intersection points are the same point). The floating-point discrepancy creates an infinitesimally short edge that cannot be assembled because the chain has already closed through a different topological path.

**Conclusion: The dropped edge is a floating-point artifact. Dropping it produces the correct Voronoi diagram.** The stall-detection fix is the right approach — it terminates when no progress can be made, and the only edges dropped are these degenerate near-zero-length artifacts.

### Verification

- All 8 existing Voronoi tests pass ✓
- No edges dropped in any non-degenerate test ✓
- Cell polygons are closed and correctly partition the domain ✓
- `itkVoronoiPartitioningImageFilterTest2` passes (which the simpler PR #5400 countdown broke) ✓

File: Modules/Segmentation/Voronoi/test/itkVoronoiDiagram2DInfiniteLoopTest.cxx (hunk 1 above)
Comment (hjmjohnson) [reply Modules/Segmentation/Voronoi/test/itkVoronoiDiagram2DInfiniteLoopTest.cxx]: report generated and code documented with description of the old failure mode and remdiation paths.

File: Modules/Segmentation/Voronoi/test/CMakeLists.txt [hunk 2]
```diff
@@ -4,11 +4,19 @@ set(
   itkVoronoiSegmentationImageFilterTest.cxx
   itkVoronoiSegmentationRGBImageFilterTest.cxx
   itkVoronoiDiagram2DTest.cxx
+  itkVoronoiDiagram2DInfiniteLoopTest.cxx
   itkVoronoiPartitioningImageFilterTest.cxx
 )
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/Segmentation/Voronoi/test/CMakeLists.txt:9]: Fixed.

File: Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.hxx [hunk 3]
```diff
@@ -353,12 +397,30 @@ VoronoiDiagram2DGenerator<TCoordinate>::ConstructDiagram()
...
+    // After assembly, all edges for this cell should have been either
+    // attached to the chain or identified as degenerate artifacts.
+    // Any remaining edges indicate an unexpected algorithmic failure.
+    if (!rawEdges[i].empty())
+    {
+      itkExceptionMacro("VoronoiDiagram2DGenerator::ConstructDiagram: "
+                        << rawEdges[i].size() << " non-degenerate edge(s) could not be "
+                        << "assembled into cell " << i << " boundary chain. "
+                        << "This indicates an unexpected geometric configuration.");
     }
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.hxx:424]: The itkException should never happen with the new code. It is a fall back case for if another unhandled behavior happens.

**Review by dzenanz — APPROVED** [review]
