### PR TITLE
BUG: Add `itk::GaussianOperator` debug methods

### LINKED ISSUE #3430: `itkDebugMacro` errors in `itk::GaussianOperator`
### Description

`this->GetDebug()` is invalid when used in `itkDebugMacro` in `itk::GaussianOperator`. The debug statement was reduced from a warning statement in [https://github.com/InsightSoftwareConsortium/ITK/pull/3423](https://github.com/InsightSoftwareConsortium/ITK/pull/3423).

### Steps to Reproduce

[CDash Expected Nightly Builds](https://open.cdash.org/viewBuildError.php?buildid=7917060)

### Expected behavior

No errors

### Actual behavior

```none
In file included from /Users/builder/external[Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx:22](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx#L22):
In file included from /Users/builder/external[Modules/Core/Common/include/itkGaussianOperator.h:192](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkGaussianOperator.h#L192):
/Users/builder/external[Modules/Core/Common/include/itkGaussianOperator.hxx:55](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkGaussianOperator.hxx#L55):7: error: no member named 'GetDebug' in 'itk::GaussianOperator<float, 3, itk::NeighborhoodAllocator<float> >'
      itkDebugMacro(<< "Kernel size has exceeded the specified maximum width of " << m_MaximumKernelWidth
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] /Users/builder/external[Modules/Core/Common/include/itkMacro.h:489](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkMacro.h#L489):17: note: expanded from macro 'itkDebugMacro'
      if (this->GetDebug() && itk::Object::GetGlobalWarningDisplay())          \
          ~~~~  ^
[CTest: warning matched] /Users/builder/external[Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx:59](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx#L59):21: note: in instantiation of member function 'itk::GaussianOperator<float, 3, itk::NeighborhoodAllocator<float> >::GenerateCoefficients' requested here
  auto * oper = new NeighborhoodOperatorType;
                    ^
1 error generated.
```

### Reproducibility

Linux CI passed but expected nightly builds fail

### Versions

`master`

### Environment

Linux, macOS

### Additional Information

Need to investigate where `this->GetDebug` is commonly defined, likely outside of `itk::GaussianOperator` inheritance hierarchy. Mostly likely resolution is to 1) remove printout entirely from `itk::GaussianOperator` and 2) document in `itkDebugMacro` that the macro is only valid to be used in classes inheriting from a certain base.

### PR DESCRIPTION
**Pull request by tbirdso**
Resolves #3430 by mimicking `itk::Object` debug interface methods so that `itkDebugMacro` implements valid debug code in `itk::GaussianOperator`.

`itk::GaussianOperator` inherits from the base `itk::Neighborhood` which is a lightweight object not inheriting from `itk::Object` or `itk::LightObject`. `itk::GaussianOperator` is more complex than other neighborhoods in that it takes in several user parameters and dynamically generates a discrete ND kernel function. In order to preserve the lightweight design of other `itk::Neighborhood` derivative classes while providing insight into the more complex inner workings of `itk::GaussianOperator`, it is reasonable to re-implement the `itk::Object` debug interface at the `itk::GaussianOperator` level.

Depends on #3431 hotfix.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by tbirdso** [comment]
@Leengit if you have time would you please try building this branch? CI checks passed in #3423 which originally introduced the error, so it seems like a different build system is needed to verify. I am working on verifying whether `master` fails without the hotfix on my Linux system, if so I will use my local system to verify as well.

**Comment by Leengit** [comment]
@tbirdso I am building and will let you know.

File: Modules/Core/Common/include/itkGaussianOperator.h [hunk 1]
```diff
@@ -142,6 +142,19 @@ class ITK_TEMPLATE_EXPORT GaussianOperator : public NeighborhoodOperator<TPixel,
...
 
+  /** Get the value of the debug flag.  */
+  bool
+  GetDebug()
+  {
+    return m_Debug;
+  }
+  /** Set the value of the debug flag. A non-zero value turns debugging on. */
+  void
+  SetDebug(bool debugFlag)
```
Comment (Leengit) [inline Modules/Core/Common/include/itkGaussianOperator.h:153]: I didn't check similar functions in ITK, so maybe this is a stupid question.  Would it be appropriate to have `debugFlag` default to `true`?

**Comment by Leengit** [comment]
@tbirdso It builds to completion on my setup:
Linux 5.13.0-41-generic #46\~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc (Ubuntu 9.4.0-1ubuntu1\~20.04.1) 9.4.0
ninja 1.10.0

File: Modules/Core/Common/include/itkGaussianOperator.h [hunk 2]
```diff
@@ -142,6 +142,19 @@ class ITK_TEMPLATE_EXPORT GaussianOperator : public NeighborhoodOperator<TPixel,
     os << indent << "MaximumKernelWidth: " << m_MaximumKernelWidth << std::endl;
   }
 
+  /** Get the value of the debug flag.  */
+  bool
+  GetDebug()
```
[the remark this answers is not in the document]
Comment (tbirdso) [reply Modules/Core/Common/include/itkGaussianOperator.h:149]: Amended to mention `itk::Object` interface and `itkDebugMacro` motivation inline, I will comment on virtual members in the PR description.

File: Modules/Core/Common/include/itkGaussianOperator.h (hunk 1 above)
Comment (tbirdso) [reply Modules/Core/Common/include/itkGaussianOperator.h:155]: Good question, `debugFlag` defaults to `false` in `itk::Object` and should be the same here. We want developers to be able to access extra debug info when something is going wrong, but the original motivation in #3423 was to make `itk::GaussianOperator` less verbose because the "warning" was simply informing the user that the kernel was behaving according to user specifications.

Comment (Leengit) [reply Modules/Core/Common/include/itkGaussianOperator.h:155]: Definitely `m_Debug` should default to `false`.  My question was about the `debugFlag` argument to `SetDebug`, so that `this->SetDebug(true)` and `this->SetDebug()` do the same thing.

File: Modules/Core/Common/include/itkGaussianOperator.h [hunk 3]
```diff
@@ -142,6 +142,21 @@ class ITK_TEMPLATE_EXPORT GaussianOperator : public NeighborhoodOperator<TPixel,
     os << indent << "MaximumKernelWidth: " << m_MaximumKernelWidth << std::endl;
   }
 
+  /** Get the value of the debug flag.
+   *  Mimics the itk::Object interface so that itkDebugMacro
+   *  can be used in selective printouts from Gaussian kernel generation.*/
+  bool
+  GetDebug()
```
Comment (Leengit) [inline Modules/Core/Common/include/itkGaussianOperator.h:149]: Both `GetDebug` and `SetDebug` should be defined as `const` methods.

File: Modules/Core/Common/include/itkGaussianOperator.h (hunk 1 above)
Comment (tbirdso) [reply Modules/Core/Common/include/itkGaussianOperator.h:155]: See above -- I can't find other examples of `this->SetDebug()` in ITK and I would rather avoid introducing it here as I don't think the default parameter is intuitive.

Comment (tbirdso) [reply Modules/Core/Common/include/itkGaussianOperator.h]: I have added `DebugOn` and `DebugOff` as alternatives requiring no parameters. These mimic the interface in `itk::Object`.

**Review by Leengit — APPROVED** [review]
Thank you.

**Review by thewtex — APPROVED** [review]
