### PR TITLE
BUG: eigen3 and hdf5 fixes for windows and R

### LINKED ISSUE #66: Building ITK on Windows
### Building ITK on Windows (through R)

I'm trying to build ITK on Windows, through R in the ITKR package (https://github.com/muschellij2/ITKR).  I'm testing this through appveyor (https://ci.appveyor.com/project/muschellij2/itkr).  I'm getting the following error: 

```
[ 73%] Building C object Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Defl.c.obj
In file included from C:\run\ITKR.Rcheck\00_pkg_src\ITKR\src\itks\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5private.h:615:0,
                 from C:\run\ITKR.Rcheck\00_pkg_src\ITKR\src\itks\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Defl.c:29:
C:\run\ITKR.Rcheck\00_pkg_src\ITKR\src\itks\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Defl.c: In function 'H5D__efl_read':
C:\run\ITKR.Rcheck\00_pkg_src\ITKR\src\itks\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5win32defs.h:57:66: error: expected expression before ')' token
 #define HDopen(S,F,...)       _open(S, F | _O_BINARY, __VA_ARGS__)
                                                                  ^
C:\run\ITKR.Rcheck\00_pkg_src\ITKR\src\itks\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Defl.c:291:18: note: in expansion of macro 'HDopen'
         if((fd = HDopen(full_name, O_RDONLY)) < 0)
                  ^
Modules\ThirdParty\HDF5\src\itkhdf5\src\CMakeFiles\hdf5-static.dir\build.make:770: recipe for target 'Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Defl.c.obj' failed
```

This worked using commit 4f89edd8334da198099c686b993ec9f9f12dccdf, but not the latest or anything with respect to v5.0.

### Steps to Reproduce

The steps can be seen here: https://ci.appveyor.com/project/muschellij2/itkr

1.   The main configure script is https://github.com/muschellij2/ITKR/blob/master/configure.win
2.  The `make` version is `mingw32-make`, and the Makevars necessary to reproduce are: https://github.com/muschellij2/ITKR/blob/master/src/Makevars.win
3.  See the attached `00install.txt` file below.

### Expected behavior

Successful build such as https://ci.appveyor.com/project/muschellij2/itkr/build/1.0.278

### Actual behavior

Build failure such as https://ci.appveyor.com/project/muschellij2/itkr/build/1.0.282

### Reproducibility

100% of the builds with 

### Versions

ITK_VERSION_MAJOR = 5
ITK_VERSION_MINOR = 0
ITK_VERSION_PATCH = 0

### Environment

Windows on Appveyor (I believe Windows Server 2012 R2	)

### Additional Information

I've uploaded the CMakeLists and the installation output
[CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/files/2412445/CMakeLists.txt)
[00install.txt](https://github.com/InsightSoftwareConsortium/ITK/files/2412450/00install.txt)

### PR DESCRIPTION
**Pull request by muschellij2**
## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

File: Modules/ThirdParty/HDF5/src/itkhdf5/src/H5win32defs.h [hunk 1]
```diff
@@ -150,6 +158,7 @@ extern "C" {
 #define HDpthread_self_ulong() ((unsigned long)GetCurrentThreadId())
 
 #ifndef H5_HAVE_MINGW
```
Comment (thewtex) [inline Modules/ThirdParty/HDF5/src/itkhdf5/src/H5win32defs.h]: We have `#ifndef H5_HAVE_MINGW`-- maybe mistaken for `#ifdef H5_HAVE_MINGW`?

What if we move this line to line 108,

```
#else
// For MinGW, etc.
#define HDopen(S,F,M)       _open(S, F | _O_BINARY, M)
#endif /* H5_HAVE_VISUAL_STUDIO */
```

?

Comment (thewtex) [reply Modules/ThirdParty/HDF5/src/itkhdf5/src/H5win32defs.h:160]: Pushing this...

**Comment by thewtex** [comment]
After a restart of a couple of the builds, they all now pass! :tada: 

@muschellij2 thank you for your patience and persistence in getting this fixed. Also, thank you for maintaining ITKR -- an awesome package! :-)
