### PR TITLE
BUG: Fix ImageRegionSplitters with zero sized image

### LINKED ISSUE #2741: LabelImageToLabelMapFilter takes a long time to complete on an empty image
The LabelImageToLabelMapFilter takes a long time to complete on an empty image.

The following code snippet can reproduce the bug.

     auto p_filter = itk::LabelImageToLabelMapFilter<itk::Image<unsigned char, 3>>::New();
     auto p_image = itk::Image<unsigned char, 3>::New();
     p_image->SetRegions(itk::Size<3>{ 0, 0, 0 });
     p_image->Allocate(true);
 
     p_filter->SetInput(p_image);     
     p_filter->Update(); 

Takes about 16 seconds to complete on my PC.

```none
```

### Reproducibility

ITK version 5.1.2

Windows, CMake 3.18.2, Visual Studio 16.7.2

### PR DESCRIPTION
**Pull request by blowekamp**
When the image had a zero size, undefined results of division by zero
occoured. For both the ImageRegionSplitterSlowDimension and the
ImageRegionSplitterDirection classes when a region's size is zero, the
region has one "split" region of a zero sized region.

closes #2741

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

File: Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx [hunk 1]
```diff
@@ -131,5 +145,8 @@ itkLabelImageToLabelMapFilterTest(int argc, char * argv[])
 
   conversion->Print(std::cout);
 
+  zeroSizeCase();
```
Comment (dzenanz) [inline Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx:148]: Return value of `zeroSizeCase` is ignored. Maybe make it a void function or do a `return zeroSizeCase();` here?

**Review by dzenanz — APPROVED** [review]
Looks good.

File: Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx (hunk 1 above)
Comment (blowekamp) [reply Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx:148]: done

**Review by hjmjohnson — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]
