### PR TITLE
ENH: fix Python multi-processing hang on unix

### LINKED ISSUE #2069: ITK Python Pool Threader deadlocks with multiprocess module
ITK Python is deadlocking when using with heavy weight process in the `multiprocess` python module.

The following is simplified from  SimpleITK/SimpleITK#1239.

The below code produces the deadlock for everything we have testing except MacOS with Python 3.8.

ITK Python version 5.1.post1 was used. 

```
#!/usr/bin/env python

import multiprocessing as mp
import numpy as np
import os
import threading
import itk

num_images = 2


def f( fname ):
    image = itk.imread(fname)


    print("Resampling {} pid: {} {}...".format(fname, os.getpid(), threading.get_ident(),fname))
    resampled = itk.resample_image_filter(image, reference_image=image, use_reference_image=True)

    return image # resampled


if __name__ == '__main__':

    paths = []
    for i in range(num_images):
        image = sitk.Image(10,11,12, sitk.sitkUInt8)
        path = f'/tmp/image_{i}.nii'
        sitk.WriteImage(image, path)
        paths.append(path)

    #print("GlobalDefaultThreader: {}".format(sitk.ProcessObject_GetGlobalDefaultThreader()))
    #print("GlobalNumberOfThreads: {}".format(sitk.ProcessObject_GetGlobalDefaultNumberOfThreads()))

    print("main pid: {} {}".format(os.getpid(), threading.get_ident()))


    f(paths[0])

    with mp.Pool(1) as p:
        p.map(f, paths)
```

Setting the global default threader to "platform" does not produce a deadlock.
Setting the resample to only use 1 work unit does not produce a deadlock.

It may be interesting to test ITK 4.x with the threader explicitly set to the pool.

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #2069.

_Initial (**old**) description:_

This turns a hang into:
```text
(pyEnv) dzenan@corista:~/nn_work_dir$ python itkMultiProcessingMONAI.py 
main pid: 2578395 140116265719616
Resampling image_0.nii pid: 2578395 140116265719616...
Resampling image_0.nii pid: 2578404 140116265719616...
Resampling image_1.nii pid: 2578404 140116265719616...
In ThreadPool::atfork_prepareIn ThreadPool::atfork_resumeTraceback (most recent call last):
  File "itkMultiProcessingMONAI.py", line 44, in <module>
    p.map(f, paths)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<itk.itkImagePython.itkImageUC3; proxy of <Swig Object of type 'itkImageUC3 *' at 0x7f6ee94955a0> >]'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'
(pyEnv) dzenan@corista:~/nn_work_dir$
```

### CODE REVIEW

File: Modules/Core/Common/src/itkThreadPool.cxx [hunk 1]
```diff
@@ -154,6 +158,23 @@ ThreadPool::~ThreadPool()
   }
 }
 
+void
+ThreadPool::atfork_prepare()
+{
+  printf("In ThreadPool::atfork_prepare");
```
Comment (hjmjohnson) [inline Modules/Core/Common/src/itkThreadPool.cxx:164]: Debugging comments should be removed.

File: Modules/Core/Common/src/itkThreadPool.cxx [hunk 2]
```diff
@@ -154,6 +158,23 @@ ThreadPool::~ThreadPool()
...
+  m_PimplGlobals->m_ThreadPoolInstance->CleanUp();
+}
+
+void
+ThreadPool::atfork_resume()
+{
+  printf("In ThreadPool::atfork_resume");
```
Comment (hjmjohnson) [inline Modules/Core/Common/src/itkThreadPool.cxx:171]: Debugging comments should be removed.

**Review by hjmjohnson — DISMISSED** [review]

File: Modules/Core/Common/src/itkThreadPool.cxx (hunk 1 above)
Comment (dzenanz) [reply Modules/Core/Common/src/itkThreadPool.cxx:164]: Once this PR gets to a working stage, I will remove them. Currently, they don't get printed.

File: Modules/Core/Common/include/itkThreadPool.h [hunk 3]
```diff
@@ -124,13 +124,23 @@ auto result = pool->AddWork([](int param) { return param; }, 7);
...
-  ~ThreadPool() override;
+
+  /** Stop the pool and release threads. To be called by the destructor and atfork. */
+  void
+  CleanUp();
+
+  ~ThreadPool() override { this->CleanUp(); }
+
+  static void
+  atfork_prepare();
```
Comment (thewtex) [inline Modules/Core/Common/include/itkThreadPool.h:141]: Per style guidelines: `atfork_prepare` -> `PrepareForFork`

File: Modules/Core/Common/include/itkThreadPool.h [hunk 4]
```diff
@@ -124,13 +124,23 @@ auto result = pool->AddWork([](int param) { return param; }, 7);
...
+  static void
+  atfork_resume();
```
Comment (thewtex) [inline Modules/Core/Common/include/itkThreadPool.h:143]: Per style guidelines: `atfork_resume` -> `ResumeFromFork`

File: Modules/Core/Common/include/itkThreadPool.h (hunk 3 above)
Comment (dzenanz) [reply Modules/Core/Common/include/itkThreadPool.h:141]: Sure, I can do that. Do you have any advice about overcoming `multiprocessing.pool.MaybeEncodingError: Error sending result: '[<itk.itkImagePython.itkImageUC3; proxy of <Swig Object of type 'itkImageUC3 *' at 0x7f6ee94955a0> >]'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'`? This is when invoking the [repro script](https://github.com/InsightSoftwareConsortium/ITK/issues/2069#issuecomment-754122517).

**Comment by blowekamp** [comment]
After a fork, the PID changes and the old threads are no longer valid. A `GetThreadPool` method should keep track of the PID, and create a new thread pool when the PID changes.

**Comment by blowekamp** [comment]
Am I understanding correctly that with this PR, when a fork occurs, the all threads are terminated in the parent, and new threads are recreated in both new processes? I would expect the parent keeps it's threads and the child process "abandons" the parents threads and keeps new ones.

**Comment by dzenanz** [comment]
> parent keeps it's threads and the child process "abandons" the parents threads

That might be possible, but with more experimentation/effort. The only thing I know of which forks with ITK is Python multiprocessing. And I am trying to address a hang in this situation, with minimal effort. Stopping and cleaning up the thread pool before the fork greatly simplifies the reasoning.

File: Modules/Core/Common/include/itkThreadPool.h (hunk 3 above)
Comment (thewtex) [reply Modules/Core/Common/include/itkThreadPool.h:141]: That issue is discussed in #1091 #1948

**Comment by dzenanz** [comment]
I guess that #1948 is a blocker for this. Now waiting for that to be done before continuing work on this.

**Comment by blowekamp** [comment]
@dzenanz I think if you take the test code from #2069, and just write the image instead of returning it, the pool issue should still be reproduced. This would separate this issue from #1948, to move part of it forward.

**Comment by dzenanz** [comment]
@blowekamp you are right! Changing return to imwrite avoids pickling, thus allowing me to verify this fix works. I cleaned it up as per Hans' and Matt's suggestions. Please re-review.

**Review by thewtex — APPROVED** [review]
:tada:

**Comment by thewtex** [comment]
Applied to the `release` branch
