### PR TITLE
COMP: Fix invalid wrap combinations

### LINKED ISSUE #2152: IPO Python wrapping compiler warnings
### Description

Recent compilation option changes (IPO turn on I think) now expose some compiler warnings.

### Steps to Reproduce

Build with cmake 3.18, python on Ubutu 18.04

### Expected behavior

Clean build with no warnings

### Actual behavior
See warnings at bottom issue in the "Additional Information section"

### Reproducibility

100% of time on Ubuntu 18.04 with cmake 3.18 (and IPO ?).

### Versions
ITK master branch as of 2020-12-05

### Environment
Ubuntu 18.04

/usr/bin/c++ --version 
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake --version 
cmake version 3.18.4

### Additional Information
```
[377/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKEigenPython.so
/home/johnsonhj/Dashboard/src/ITK/Modules/Numerics/Eigen/include/itkEigenAnalysis2DImageFilter.hxx: In member function ‘GenerateData’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkVector.hxx:109:25: warning: ‘MEM[(const ValueType &)&eigenVector].m_InternalArray[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     const RealValueType value = (*this)[i];
                         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Numerics/Eigen/include/itkEigenAnalysis2DImageFilter.hxx: In member function ‘GenerateData’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkVector.hxx:109:25: warning: ‘MEM[(const ValueType &)&eigenVector].m_InternalArray[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     const RealValueType value = (*this)[i];
                         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkVector.hxx:109:25: warning: ‘MEM[(const ValueType &)&eigenVector].m_InternalArray[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
[605/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKIOSpatialObjectsPython.so
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member function ‘EvaluatePosition’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:588:36: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       const CoordRepType t = pt[j] * weights[i];
                                    ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:586:32: note: within this loop
     for (unsigned int j = 0; j < Self::CellDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:361:26: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         fcol[j] += pt[j] * weights[i];
                          ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:359:34: note: within this loop
       for (unsigned int j = 0; j < Self::CellDimension; ++j)
                                  ^
[623/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKIOMeshBasePython.so
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member function ‘EvaluatePosition’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:588:36: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       const CoordRepType t = pt[j] * weights[i];
                                    ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:586:32: note: within this loop
     for (unsigned int j = 0; j < Self::CellDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:361:26: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         fcol[j] += pt[j] * weights[i];
                          ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:359:34: note: within this loop
       for (unsigned int j = 0; j < Self::CellDimension; ++j)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member function ‘EvaluatePosition’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:588:36: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       const CoordRepType t = pt[j] * weights[i];
                                    ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:586:32: note: within this loop
     for (unsigned int j = 0; j < Self::CellDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:361:26: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         fcol[j] += pt[j] * weights[i];
                          ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:359:34: note: within this loop
       for (unsigned int j = 0; j < Self::CellDimension; ++j)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member function ‘EvaluatePosition’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:588:36: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       const CoordRepType t = pt[j] * weights[i];
                                    ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:586:32: note: within this loop
     for (unsigned int j = 0; j < Self::CellDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:361:26: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         fcol[j] += pt[j] * weights[i];
                          ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:359:34: note: within this loop
       for (unsigned int j = 0; j < Self::CellDimension; ++j)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member function ‘EvaluatePosition’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:588:36: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       const CoordRepType t = pt[j] * weights[i];
                                    ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:586:32: note: within this loop
     for (unsigned int j = 0; j < Self::CellDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:361:26: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         fcol[j] += pt[j] * weights[i];
                          ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:359:34: note: within this loop
       for (unsigned int j = 0; j < Self::CellDimension; ++j)
                                  ^
[635/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKPDEDeformableRegistrationPython.so
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:242:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / denominator;
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:240:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:180:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:178:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx: In member function ‘CopyInputToOutput’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:228:7: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       zeros[j] = 0;
       ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:226:32: note: within this loop
     for (unsigned int j = 0; j < ImageDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx: In member function ‘CopyInputToOutput’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:228:7: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       zeros[j] = 0;
       ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:226:32: note: within this loop
     for (unsigned int j = 0; j < ImageDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:242:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / denominator;
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:240:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:180:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:178:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:242:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / denominator;
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:240:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:180:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx:178:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx: In member function ‘CopyInputToOutput’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:228:7: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       zeros[j] = 0;
       ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx:226:32: note: within this loop
     for (unsigned int j = 0; j < ImageDimension; j++)
                                ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:373:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / (gradientMagnitude + m_Alpha);
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:371:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:260:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:258:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:373:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / (gradientMagnitude + m_Alpha);
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:371:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:260:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:258:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:373:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     update[j] = speedValue * gradient[j] / (gradientMagnitude + m_Alpha);
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:371:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:260:5: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
     mappedPoint[j] += it.GetCenterPixel()[j];
     ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx:258:30: note: within this loop
   for (unsigned int j = 0; j < ImageDimension; j++)
                              ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:209:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:207:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:191:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:29: warning: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         mappedNeighPoint[j] += displacement[j];
                             ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:189:29: note: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ was declared here
       DisplacementPixelType displacement = field->GetPixel(tmpIndex);
                             ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:209:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:207:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:191:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:29: warning: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         mappedNeighPoint[j] += displacement[j];
                             ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:189:29: note: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ was declared here
       DisplacementPixelType displacement = field->GetPixel(tmpIndex);
                             ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx: In member function ‘ComputeUpdate’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:209:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:207:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:9: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         mappedNeighPoint[j] += displacement[j];
         ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:191:34: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
                                  ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:193:29: warning: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         mappedNeighPoint[j] += displacement[j];
                             ^
/home/johnsonhj/Dashboard/src/ITK/Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx:189:29: note: ‘MEM[(ValueType &)&displacement].m_InternalArray[2]’ was declared here
       DisplacementPixelType displacement = field->GetPixel(tmpIndex);
                             ^
[645/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKMathematicalMorphologyPython.so
[646/649] Linking CXX shared module Wrapping/Generators/Python/itk/_ITKImageGridPython.so
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx: In member function ‘DynamicThreadedGenerateData’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:309:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:307:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:339:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:337:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx: In member function ‘DynamicThreadedGenerateData’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:309:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:307:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:339:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:337:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx: In member function ‘DynamicThreadedGenerateData’:
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:309:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:307:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:339:0: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         point[j] += displacement[j];
 
/home/johnsonhj/Dashboard/src/ITK/Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:337:0: note: within this loop
       for (unsigned int j = 0; j < ImageDimension; j++)
 

```

### PR DESCRIPTION
**Pull request by hjmjohnson**
Resolves #2152 

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] REMOVED  Python wrapping to INVALID COMBINATIONS

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@dzenanz Only the last two items are related to this PR.  Will rebase once #2154 is merged.

File: Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx [hunk 1]
```diff
@@ -289,6 +289,7 @@ WarpImageFilter<TInputImage, TOutputImage, TDisplacementField>::DynamicThreadedG
   PointType                                     point;
```
Comment (dzenanz) [inline Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:289]: In commit message: ininitialized -> uninitialized

File: Modules/Numerics/Eigen/wrapping/itkEigenAnalysis2DImageFilter.wrap [hunk 2]
```diff
@@ -1,5 +1,11 @@
 itk_wrap_class("itk::EigenAnalysis2DImageFilter" POINTER)
+  # Only vectors with 2 components are valid. Temporarily change the global vector dims list.
```
Comment (dzenanz) [inline Modules/Numerics/Eigen/wrapping/itkEigenAnalysis2DImageFilter.wrap:2]: Of the few update class wrap files, this filter seems to be the only one which is 2D-only. So these changes make sense.

File: Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap [hunk 3]
```diff
@@ -1,5 +1,16 @@
 itk_wrap_class("itk::DemonsRegistrationFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Only vectors with 2 components are valid. Temporarily change the global vector dims list.
```
Comment (dzenanz) [inline Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap:6]: Why only 2? It should work for many dimensions.

**Review by dzenanz — CHANGES_REQUESTED** [review]

File: Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap (hunk 3 above)
Comment (hjmjohnson) [reply Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap:6]: Comment fixed here and other similar places.

**Comment by hjmjohnson** [comment]
961 - itkJPEG2000Test06 (Failed)  FAILURE NOT RELATED.

**Comment by hjmjohnson** [comment]
@Leengit Is this solution acceptable to you?

File: Modules/Core/Common/include/itkHexahedronCell.hxx [hunk 4]
```diff
@@ -356,7 +356,7 @@ HexahedronCell<TCellInterface>::EvaluatePosition(CoordRepType *            x,
     for (unsigned int i = 0; i < Self::NumberOfPoints; ++i)
     {
       pt = points->GetElement(m_PointIds[i]);
-      for (unsigned int j = 0; j < Self::CellDimension; ++j)
+      for (unsigned int j = 0; j < PointType::Dimension; ++j)
```
Comment (Leengit) [inline Modules/Core/Common/include/itkHexahedronCell.hxx:359]: Not all loops that index the `pt` variable have had `Self::CellDimension` changed to `PointType::Dimension`.  Also not changed are the definitions of variables (e.g., `fcol`, `rcol`, `scol`, and `tcol`) that are also used in those loops.  Should they be similarly changed?  (Or more globally, but with much more speculation on my part, should the constexpr definition of `CellDimension` be changed to be `PointType::Dimension`?)

File: Modules/Core/Common/include/itkHexahedronCell.hxx [hunk 5]
```diff
@@ -581,9 +581,9 @@ HexahedronCell<TCellInterface>::EvaluateLocation(int &                     itkNo
   std::fill_n(x, Self::CellDimension, 0.0);
   for (unsigned int i = 0; i < Self::NumberOfPoints; i++)
   {
-    PointType pt = points->GetElement(m_PointIds[i]);
+    const PointType pt{ points->GetElement(m_PointIds[i]) };
```
Comment (Leengit) [inline Modules/Core/Common/include/itkHexahedronCell.hxx:584]: `PointType` is not explicitly defined in `itkHexahedronCell.h`.  Is it is coming from a superclass?  It might be more transparent to put
```c++
using PointType = TCellInterface::PointType;
```
in `itkHexahedronCell.h`.  (Or if `TCellInterface::` isn't where it is coming from, then use the correct location!)

File: Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap [hunk 6]
```diff
@@ -1,5 +1,16 @@
 itk_wrap_class("itk::WarpImageFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Vector components dimension must match image dimension. Temporarily change the global vector dims list.
+    set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap:7]: How about a more unique name (e.g., that includes `WARP_IMAGE_FILTER_`) rather than `BACKUP_`?  If someday someone else happens to use `BACKUP_` in a different file that is effectively inside or containing this loop, we'd have a heck of a time debugging that one overwrote the other.

File: Modules/Numerics/Eigen/wrapping/itkEigenAnalysis2DImageFilter.wrap [hunk 7]
```diff
@@ -1,5 +1,11 @@
...
+  set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Numerics/Eigen/wrapping/itkEigenAnalysis2DImageFilter.wrap:3]: Perhaps replace / supplement `BACKUP_` with something that includes `EIGEN_ANALYSIS_2D_IMAGE_FILTER_`.

File: Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap [hunk 8]
```diff
@@ -1,5 +1,16 @@
 itk_wrap_class("itk::DemonsRegistrationFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Vector components dimension must match image dimension. Temporarily change the global vector dims list.
+    set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap:7]: ... replace `BACKUP_` ....

**Review by Leengit — APPROVED** [review]
Looks good.  Minor changes suggested above.

File: Modules/Registration/PDEDeformable/wrapping/itkLevelSetMotionRegistrationFilter.wrap [hunk 9]
```diff
@@ -1,7 +1,18 @@
...
 # so this class is not.
 itk_wrap_class("itk::LevelSetMotionRegistrationFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Vector components dimension must match image dimension. Temporarily change the global vector dims list.
+    set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Registration/PDEDeformable/wrapping/itkLevelSetMotionRegistrationFilter.wrap:9]: ... replace `BACKUP_` ....

File: Modules/Registration/PDEDeformable/wrapping/itkPDEDeformableRegistrationFilter.wrap [hunk 10]
```diff
@@ -1,5 +1,16 @@
 itk_wrap_class("itk::PDEDeformableRegistrationFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Vector components dimension must match image dimension. Temporarily change the global vector dims list.
+    set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Registration/PDEDeformable/wrapping/itkPDEDeformableRegistrationFilter.wrap:7]: ... replace `BACKUP_` ....

File: Modules/Registration/PDEDeformable/wrapping/itkSymmetricForcesDemonsRegistrationFilter.wrap [hunk 11]
```diff
@@ -1,7 +1,18 @@
...
 # so this class is not.
 itk_wrap_class("itk::SymmetricForcesDemonsRegistrationFilter" POINTER)
-  foreach(s ${WRAP_ITK_SCALAR})
-    itk_wrap_image_filter_combinations("${s}" "${s}" "${WRAP_ITK_VECTOR_REAL}" 2+)
+  foreach(curr_dim ${ITK_WRAP_IMAGE_DIMS})
+    if(${curr_dim} LESS 1)
+        continue()
+    endif()
+    # Vector components dimension must match image dimension. Temporarily change the global vector dims list.
+    set(BACKUP_ITK_WRAP_VECTOR_COMPONENTS "${ITK_WRAP_VECTOR_COMPONENTS}")
```
Comment (Leengit) [inline Modules/Registration/PDEDeformable/wrapping/itkSymmetricForcesDemonsRegistrationFilter.wrap:9]: ... replace `BACKUP_` ....

File: Modules/Core/Common/include/itkHexahedronCell.hxx (hunk 4 above)
Comment (hjmjohnson) [reply Modules/Core/Common/include/itkHexahedronCell.hxx:359]: @Leengit I don't know this code at all.  These are the only problems that were exposed during compilation.  

Do you know this code? Could you fix this better?

File: Modules/Core/Common/include/itkHexahedronCell.hxx (hunk 5 above)
Comment (hjmjohnson) [reply Modules/Core/Common/include/itkHexahedronCell.hxx:584]: Not my code.  I don't want to learn the code just to silence compiler warnings.

File: Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap (hunk 6 above)
Comment (hjmjohnson) [reply Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap:7]: See a few lines lower where this variable is unset  so that it has very limited scope.

File: Modules/Registration/PDEDeformable/wrapping/itkSymmetricForcesDemonsRegistrationFilter.wrap (hunk 11 above)
Comment (dzenanz) [reply Modules/Registration/PDEDeformable/wrapping/itkSymmetricForcesDemonsRegistrationFilter.wrap:9]: A few lines later `BACKUP_*` gets unset, thus deleting the definition. I don't know what would be the result if `BACKUP_*` definition existed prior to this code. It would probably be undefined, but potential for problems is not that big.

File: Modules/Registration/PDEDeformable/wrapping/itkLevelSetMotionRegistrationFilter.wrap [hunk 12]
```diff
@@ -1,7 +1,18 @@
-# DemonsRegistrationFilter is wrapped with POINTER_WITH_SUPERCLASS
+# LevelSetMotionRegistrationFilter is wrapped with POINTER_WITH_SUPERCLASS
```
Comment (dzenanz) [inline Modules/Registration/PDEDeformable/wrapping/itkLevelSetMotionRegistrationFilter.wrap:1]: I guess that comment was referring to this class' superclass? This change makes the comment factually incorrect, as this file wraps LevelSetMotionRegistrationFilter as POINTER on line 3.

File: Modules/Core/Common/include/itkHexahedronCell.hxx (hunk 4 above)
Comment (hjmjohnson) [reply Modules/Core/Common/include/itkHexahedronCell.hxx:359]: Requested changes are outside the scope of this patch set.  They should be made into an issue and addressed by someone who knows the HexahedronCell code better.

File: Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap (hunk 6 above)
Comment (Leengit) [reply Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap:7]: Agreed, chances are that `itk_wrap_image_filter_combinations` (between the set and unset) does not and will not use a variable named `BACKUP_ITK_WRAP_VECTOR_COMPONENTS`.  Likewise agreed, chances are that cmake code before this is executed is not and will not be setting that variable for use after this code is executed.

File: Modules/Core/Common/include/itkHexahedronCell.hxx [hunk 13]
```diff
@@ -581,9 +581,9 @@ HexahedronCell<TCellInterface>::EvaluateLocation(int &                     itkNo
...
 
-    for (unsigned int j = 0; j < Self::CellDimension; j++)
+    for (unsigned int j = 0; j < PointType::Dimension; j++)
```
Comment (thewtex) [inline Modules/Core/Common/include/itkHexahedronCell.hxx:586]: Good find -- certain compiler combinations were flagging this with a warning, if I recall correctly.

**Review by thewtex — APPROVED** [review]
