### PR TITLE
Fix Unique LabelMap filters producing non-unique labels and causing concurrent pixel writes.

### LINKED ISSUE #3031: itkStatisticsUniqueLabelMapFilterTest1 test fails under TSan (Thread Sanitizer)
Two different threads (`T16` then `T10`) decide to write to the same pixel.  Perhaps they are writing the same colour, but that's still undefined behaviour.

Perhaps the bug is that they should be writing to different pixels?  Otherwise, it seems that some mutex or other synchronization would need to be added.

Full TSan output is:

```
Trying writer->Update()
libpng warning: sCAL: invalid unit
libpng warning: sCAL: invalid unit
-------- Start StatisticsUniqueLabelMapFilter "filter" StatisticsUniqueLabelMapFilter (0x7b4c00001880)
  RTTI typeinfo:   itk::StatisticsUniqueLabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> > >
  Reference Count: 3
  Modified Time: 309
  Debug: Off
  Object Name: 
  Observers: 
    StartEvent(SimpleMemberCommand)
    EndEvent(SimpleMemberCommand)
    ProgressEvent(SimpleMemberCommand)
    IterationEvent(SimpleMemberCommand)
    AbortEvent(SimpleMemberCommand)
  Inputs: 
    Primary: (0x7b5000001c00) *
  Indexed Inputs: 
    0: Primary (0x7b5000001c00)
  Required Input Names: Primary
  NumberOfRequiredInputs: 1
  Outputs: 
    Primary: (0x7b5000001e00)
  Indexed Outputs: 
    0: Primary (0x7b5000001e00)
  NumberOfRequiredOutputs: 1
  Number Of Work Units: 64
  ReleaseDataFlag: Off
  ReleaseDataBeforeUpdateFlag: Off
  AbortGenerateData: Off
  Progress: 0
  Multithreader: 
    RTTI typeinfo:   itk::PoolMultiThreader
    Reference Count: 1
    Modified Time: 295
    Debug: Off
    Object Name: 
    Observers: 
      none
    Number of Work Units: 64
    Number of Threads: 16
    Global Maximum Number Of Threads: 128
    Global Default Number Of Threads: 16
    Global Default Threader Type: itk::MultiThreaderBaseEnums::Threader::Pool
    SingleMethod: 0
    SingleData: 0x0
  DynamicMultiThreading: On
  CoordinateTolerance: 1e-06
  DirectionTolerance: 1e-06
  InPlace: On
  The input and output to this filter are the same type. The filter can be run in place.
  ReverseOrdering: 0
  Attribute: NumberOfPixels (100)
Progress  | 0 | 1
Filter took 0.0329771 seconds.
-------- End StatisticsUniqueLabelMapFilter "filter" 
StatisticsUniqueLabelMapFilter (0x7b4c00001880)
  RTTI typeinfo:   itk::StatisticsUniqueLabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> > >
  Reference Count: 3
  Modified Time: 309
  Debug: Off
  Object Name: 
  Observers: 
    StartEvent(SimpleMemberCommand)
    EndEvent(SimpleMemberCommand)
    ProgressEvent(SimpleMemberCommand)
    IterationEvent(SimpleMemberCommand)
    AbortEvent(SimpleMemberCommand)
  Inputs: 
    Primary: (0x7b5000001c00) *
  Indexed Inputs: 
    0: Primary (0x7b5000001c00)
  Required Input Names: Primary
  NumberOfRequiredInputs: 1
  Outputs: 
    Primary: (0x7b5000001e00)
  Indexed Outputs: 
    0: Primary (0x7b5000001e00)
  NumberOfRequiredOutputs: 1
  Number Of Work Units: 64
  ReleaseDataFlag: Off
  ReleaseDataBeforeUpdateFlag: Off
  AbortGenerateData: Off
  Progress: 1
  Multithreader: 
    RTTI typeinfo:   itk::PoolMultiThreader
    Reference Count: 1
    Modified Time: 295
    Debug: Off
    Object Name: 
    Observers: 
      none
    Number of Work Units: 64
    Number of Threads: 16
    Global Maximum Number Of Threads: 128
    Global Default Number Of Threads: 16
    Global Default Threader Type: itk::MultiThreaderBaseEnums::Threader::Pool
    SingleMethod: 0
    SingleData: 0x0
  DynamicMultiThreading: On
  CoordinateTolerance: 1e-06
  DirectionTolerance: 1e-06
  InPlace: On
  The input and output to this filter are the same type. The filter can be run in place.
  ReverseOrdering: 0
  Attribute: NumberOfPixels (100)
==================
WARNING: ThreadSanitizer: data race (pid=41828)
  Write of size 1 at 0x7bc00005cc57 by thread T10:
    #0 itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&) itkImage.h:211 (ITKLabelMapTestDriver:x86_64+0x100055d59)
    #1 itk::LabelMapToLabelImageFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::ThreadedProcessLabelObject(itk::StatisticsLabelObject<unsigned char, 2u>*) itkLabelMapToLabelImageFilter.hxx:57 (ITKLabelMapTestDriver:x86_64+0x100587160)
    #2 itk::LabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::DynamicThreadedGenerateData(itk::ImageRegion<2u> const&) itkLabelMapFilter.hxx:113 (ITKLabelMapTestDriver:x86_64+0x1005869c8)
    #3 itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)::operator()(itk::ImageRegion<2u> const&) const itkImageSource.hxx:233 (ITKLabelMapTestDriver:x86_64+0x100013eb7)
    #4 decltype(std::__1::forward<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&>(fp)(std::__1::forward<itk::ImageRegion<2u> const&>(fp0))) std::__1::__invoke<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100013e33)
    #5 void std::__1::__invoke_void_return_wrapper<void>::__call<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100013db3)
    #6 std::__1::__function::__alloc_func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100013d63)
    #7 std::__1::__function::__func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x1000128fc)
    #8 std::__1::__function::__value_func<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1000120b6)
    #9 std::__1::function<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x100011fe8)
    #10 void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)::operator()(long const*, unsigned long const*) const itkMultiThreaderBase.h:350 (ITKLabelMapTestDriver:x86_64+0x100011ed7)
    #11 decltype(std::__1::forward<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&>(fp)(std::__1::forward<long const*>(fp0), std::__1::forward<unsigned long const*>(fp0))) std::__1::__invoke<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100011dfe)
    #12 void std::__1::__invoke_void_return_wrapper<void>::__call<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100011d48)
    #13 std::__1::__function::__alloc_func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100011c78)
    #14 std::__1::__function::__func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x100010640)
    #15 std::__1::__function::__value_func<void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x10135193a)
    #16 std::__1::function<void (long const*, unsigned long const*)>::operator()(long const*, unsigned long const*) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x101349ec3)
    #17 itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5::operator()() const itkPoolMultiThreader.cxx:271 (ITKLabelMapTestDriver:x86_64+0x1013de1aa)
    #18 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(fp)()) std::__1::__invoke<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de111)
    #19 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&, std::__1::tuple<>&, std::__1::__tuple_indices<>, std::__1::tuple<>&&) functional:2644 (ITKLabelMapTestDriver:x86_64+0x1013de0c9)
    #20 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::operator()<>() functional:2677 (ITKLabelMapTestDriver:x86_64+0x1013de089)
    #21 decltype(std::__1::forward<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(fp)()) std::__1::__invoke<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de021)
    #22 std::__1::__packaged_task_func<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>, std::__1::allocator<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5> >, void* ()>::operator()() future:1821 (ITKLabelMapTestDriver:x86_64+0x1013dd8a5)
    #23 std::__1::__packaged_task_function<void* ()>::operator()() const future:1998 (ITKLabelMapTestDriver:x86_64+0x1013d6cbf)
    #24 std::__1::packaged_task<void* ()>::operator()() future:2089 (ITKLabelMapTestDriver:x86_64+0x1013d6b6e)
    #25 std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()::operator()() const itkThreadPool.h:97 (ITKLabelMapTestDriver:x86_64+0x1013e0091)
    #26 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(fp)()) std::__1::__invoke<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e0021)
    #27 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x1013dffb1)
    #28 std::__1::__function::__alloc_func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1527 (ITKLabelMapTestDriver:x86_64+0x1013dff71)
    #29 std::__1::__function::__func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1651 (ITKLabelMapTestDriver:x86_64+0x1013de9ed)
    #30 std::__1::__function::__value_func<void ()>::operator()() const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1013a6c84)
    #31 std::__1::function<void ()>::operator()() const functional:2347 (ITKLabelMapTestDriver:x86_64+0x1013a27e9)
    #32 itk::ThreadPool::ThreadExecute() itkThreadPool.cxx:211 (ITKLabelMapTestDriver:x86_64+0x1013e0e5a)
    #33 decltype(std::__1::forward<void (*)()>(fp)()) std::__1::__invoke<void (*)()>(void (*&&)()) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e7f76)
    #34 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>&, std::__1::__tuple_indices<>) thread:342 (ITKLabelMapTestDriver:x86_64+0x1013e7e59)
    #35 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) thread:352 (ITKLabelMapTestDriver:x86_64+0x1013e760a)

  Previous write of size 1 at 0x7bc00005cc57 by thread T16:
    #0 itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&) itkImage.h:211 (ITKLabelMapTestDriver:x86_64+0x100055d59)
    #1 itk::LabelMapToLabelImageFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::ThreadedProcessLabelObject(itk::StatisticsLabelObject<unsigned char, 2u>*) itkLabelMapToLabelImageFilter.hxx:57 (ITKLabelMapTestDriver:x86_64+0x100587160)
    #2 itk::LabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::DynamicThreadedGenerateData(itk::ImageRegion<2u> const&) itkLabelMapFilter.hxx:113 (ITKLabelMapTestDriver:x86_64+0x1005869c8)
    #3 itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)::operator()(itk::ImageRegion<2u> const&) const itkImageSource.hxx:233 (ITKLabelMapTestDriver:x86_64+0x100013eb7)
    #4 decltype(std::__1::forward<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&>(fp)(std::__1::forward<itk::ImageRegion<2u> const&>(fp0))) std::__1::__invoke<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100013e33)
    #5 void std::__1::__invoke_void_return_wrapper<void>::__call<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100013db3)
    #6 std::__1::__function::__alloc_func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100013d63)
    #7 std::__1::__function::__func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x1000128fc)
    #8 std::__1::__function::__value_func<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1000120b6)
    #9 std::__1::function<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x100011fe8)
    #10 void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)::operator()(long const*, unsigned long const*) const itkMultiThreaderBase.h:350 (ITKLabelMapTestDriver:x86_64+0x100011ed7)
    #11 decltype(std::__1::forward<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&>(fp)(std::__1::forward<long const*>(fp0), std::__1::forward<unsigned long const*>(fp0))) std::__1::__invoke<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100011dfe)
    #12 void std::__1::__invoke_void_return_wrapper<void>::__call<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100011d48)
    #13 std::__1::__function::__alloc_func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100011c78)
    #14 std::__1::__function::__func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x100010640)
    #15 std::__1::__function::__value_func<void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x10135193a)
    #16 std::__1::function<void (long const*, unsigned long const*)>::operator()(long const*, unsigned long const*) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x101349ec3)
    #17 itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5::operator()() const itkPoolMultiThreader.cxx:271 (ITKLabelMapTestDriver:x86_64+0x1013de1aa)
    #18 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(fp)()) std::__1::__invoke<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de111)
    #19 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&, std::__1::tuple<>&, std::__1::__tuple_indices<>, std::__1::tuple<>&&) functional:2644 (ITKLabelMapTestDriver:x86_64+0x1013de0c9)
    #20 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::operator()<>() functional:2677 (ITKLabelMapTestDriver:x86_64+0x1013de089)
    #21 decltype(std::__1::forward<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(fp)()) std::__1::__invoke<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de021)
    #22 std::__1::__packaged_task_func<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>, std::__1::allocator<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5> >, void* ()>::operator()() future:1821 (ITKLabelMapTestDriver:x86_64+0x1013dd8a5)
    #23 std::__1::__packaged_task_function<void* ()>::operator()() const future:1998 (ITKLabelMapTestDriver:x86_64+0x1013d6cbf)
    #24 std::__1::packaged_task<void* ()>::operator()() future:2089 (ITKLabelMapTestDriver:x86_64+0x1013d6b6e)
    #25 std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()::operator()() const itkThreadPool.h:97 (ITKLabelMapTestDriver:x86_64+0x1013e0091)
    #26 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(fp)()) std::__1::__invoke<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e0021)
    #27 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x1013dffb1)
    #28 std::__1::__function::__alloc_func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1527 (ITKLabelMapTestDriver:x86_64+0x1013dff71)
    #29 std::__1::__function::__func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1651 (ITKLabelMapTestDriver:x86_64+0x1013de9ed)
    #30 std::__1::__function::__value_func<void ()>::operator()() const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1013a6c84)
    #31 std::__1::function<void ()>::operator()() const functional:2347 (ITKLabelMapTestDriver:x86_64+0x1013a27e9)
    #32 itk::ThreadPool::ThreadExecute() itkThreadPool.cxx:211 (ITKLabelMapTestDriver:x86_64+0x1013e0e5a)
    #33 decltype(std::__1::forward<void (*)()>(fp)()) std::__1::__invoke<void (*)()>(void (*&&)()) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e7f76)
    #34 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>&, std::__1::__tuple_indices<>) thread:342 (ITKLabelMapTestDriver:x86_64+0x1013e7e59)
    #35 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) thread:352 (ITKLabelMapTestDriver:x86_64+0x1013e760a)

  Location is heap block of size 65536 at 0x7bc000050000 allocated by main thread:
    #0 operator new[](unsigned long) <null>:5891680 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x6ed8b)
    #1 itk::ImportImageContainer<unsigned long, unsigned char>::AllocateElements(unsigned long, bool) const itkImportImageContainer.hxx:180 (ITKLabelMapTestDriver:x86_64+0x10001b2da)
    #2 itk::ImportImageContainer<unsigned long, unsigned char>::Reserve(unsigned long, bool) itkImportImageContainer.hxx:85 (ITKLabelMapTestDriver:x86_64+0x10001c3e5)
    #3 itk::Image<unsigned char, 2u>::Allocate(bool) itkImage.hxx:53 (ITKLabelMapTestDriver:x86_64+0x1000186f6)
    #4 itk::ImageSource<itk::Image<unsigned char, 2u> >::AllocateOutputs() itkImageSource.hxx:184 (ITKLabelMapTestDriver:x86_64+0x10000d752)
    #5 itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData() itkImageSource.hxx:215 (ITKLabelMapTestDriver:x86_64+0x10000ea7a)
    #6 itk::ProcessObject::UpdateOutputData(itk::DataObject*) itkProcessObject.cxx:1708 (ITKLabelMapTestDriver:x86_64+0x1013344a8)
    #7 itk::DataObject::UpdateOutputData() itkDataObject.cxx:376 (ITKLabelMapTestDriver:x86_64+0x101370a4d)
    #8 itk::ImageBase<2u>::UpdateOutputData() itkImageBase.hxx:263 (ITKLabelMapTestDriver:x86_64+0x10001747a)
    #9 itk::ImageFileWriter<itk::Image<unsigned char, 2u> >::Write() itkImageFileWriter.hxx:284 (ITKLabelMapTestDriver:x86_64+0x1000580ad)
    #10 itk::ImageFileWriter<itk::Image<unsigned char, 2u> >::Update() itkImageFileWriter.h:178 (ITKLabelMapTestDriver:x86_64+0x1000568f5)
    #11 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:136 (ITKLabelMapTestDriver:x86_64+0x100af9088)
    #12 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

  Thread T10 (tid=106450770, running) created by main thread at:
    #0 pthread_create <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x2933d)
    #1 std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:328 (ITKLabelMapTestDriver:x86_64+0x1013e7589)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:368 (ITKLabelMapTestDriver:x86_64+0x1013e73cc)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:360 (ITKLabelMapTestDriver:x86_64+0x1013e7300)
    #4 void std::__1::allocator<std::__1::thread>::construct<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) memory:1826 (ITKLabelMapTestDriver:x86_64+0x1013e72b8)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::__construct<std::__1::thread, void (*)()>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1718 (ITKLabelMapTestDriver:x86_64+0x1013e7268)
    #6 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::construct<std::__1::thread, void (*)()>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1561 (ITKLabelMapTestDriver:x86_64+0x1013e7118)
    #7 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::emplace_back<void (*)()>(void (*&&)()) vector:1688 (ITKLabelMapTestDriver:x86_64+0x1013e0d12)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:x86_64+0x1013e0ac6)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:x86_64+0x1013e0f49)
    #10 itk::ThreadPool::GetInstance()::$_2::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:x86_64+0x1013e620b)
    #11 decltype(std::__1::forward<itk::ThreadPool::GetInstance()::$_2>(fp)()) std::__1::__invoke<itk::ThreadPool::GetInstance()::$_2>(itk::ThreadPool::GetInstance()::$_2&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e6103)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::__execute<>(std::__1::__tuple_indices<>) mutex:622 (ITKLabelMapTestDriver:x86_64+0x1013e60d1)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::operator()() mutex:614 (ITKLabelMapTestDriver:x86_64+0x1013e6079)
    #14 void std::__1::__call_once_proxy<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >(void*) mutex:650 (ITKLabelMapTestDriver:x86_64+0x1013e5f19)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x69a0e)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:x86_64+0x1013e0681)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:x86_64+0x1013ca496)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:x86_64+0x1013ca7b9)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:x86_64+0x1013493c5)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:419 (ITKLabelMapTestDriver:x86_64+0x101348ef0)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:x86_64+0x10132bf1a)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u> >::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:x86_64+0x10000a020)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:x86_64+0x100009ef4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:x86_64+0x100009d19)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:x86_64+0x100008475)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:x86_64+0x100af8800)
    #27 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

  Thread T16 (tid=106450776, running) created by main thread at:
    #0 pthread_create <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x2933d)
    #1 std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:328 (ITKLabelMapTestDriver:x86_64+0x1013e7589)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:368 (ITKLabelMapTestDriver:x86_64+0x1013e73cc)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:360 (ITKLabelMapTestDriver:x86_64+0x1013e7300)
    #4 void std::__1::allocator<std::__1::thread>::construct<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) memory:1826 (ITKLabelMapTestDriver:x86_64+0x1013e72b8)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::__construct<std::__1::thread, void (*)()>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1718 (ITKLabelMapTestDriver:x86_64+0x1013e7268)
    #6 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::construct<std::__1::thread, void (*)()>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1561 (ITKLabelMapTestDriver:x86_64+0x1013e7118)
    #7 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::emplace_back<void (*)()>(void (*&&)()) vector:1688 (ITKLabelMapTestDriver:x86_64+0x1013e0d12)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:x86_64+0x1013e0ac6)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:x86_64+0x1013e0f49)
    #10 itk::ThreadPool::GetInstance()::$_2::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:x86_64+0x1013e620b)
    #11 decltype(std::__1::forward<itk::ThreadPool::GetInstance()::$_2>(fp)()) std::__1::__invoke<itk::ThreadPool::GetInstance()::$_2>(itk::ThreadPool::GetInstance()::$_2&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e6103)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::__execute<>(std::__1::__tuple_indices<>) mutex:622 (ITKLabelMapTestDriver:x86_64+0x1013e60d1)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::operator()() mutex:614 (ITKLabelMapTestDriver:x86_64+0x1013e6079)
    #14 void std::__1::__call_once_proxy<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >(void*) mutex:650 (ITKLabelMapTestDriver:x86_64+0x1013e5f19)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x69a0e)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:x86_64+0x1013e0681)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:x86_64+0x1013ca496)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:x86_64+0x1013ca7b9)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:x86_64+0x1013493c5)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:419 (ITKLabelMapTestDriver:x86_64+0x101348ef0)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:x86_64+0x10132bf1a)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u> >::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:x86_64+0x10000a020)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:x86_64+0x100009ef4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:x86_64+0x100009d19)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:x86_64+0x100008475)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:x86_64+0x100af8800)
    #27 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

SUMMARY: ThreadSanitizer: data race itkImage.h:211 in itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&)
==================
==================
WARNING: ThreadSanitizer: data race (pid=41828)
  Write of size 1 at 0x7bc00005cd56 by thread T10:
    #0 itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&) itkImage.h:211 (ITKLabelMapTestDriver:x86_64+0x100055d59)
    #1 itk::LabelMapToLabelImageFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::ThreadedProcessLabelObject(itk::StatisticsLabelObject<unsigned char, 2u>*) itkLabelMapToLabelImageFilter.hxx:57 (ITKLabelMapTestDriver:x86_64+0x100587160)
    #2 itk::LabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> >, itk::Image<unsigned char, 2u> >::DynamicThreadedGenerateData(itk::ImageRegion<2u> const&) itkLabelMapFilter.hxx:113 (ITKLabelMapTestDriver:x86_64+0x1005869c8)
    #3 itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)::operator()(itk::ImageRegion<2u> const&) const itkImageSource.hxx:233 (ITKLabelMapTestDriver:x86_64+0x100013eb7)
    #4 decltype(std::__1::forward<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&>(fp)(std::__1::forward<itk::ImageRegion<2u> const&>(fp0))) std::__1::__invoke<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100013e33)
    #5 void std::__1::__invoke_void_return_wrapper<void>::__call<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&, itk::ImageRegion<2u> const&>(itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)&&&, itk::ImageRegion<2u> const&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100013db3)
    #6 std::__1::__function::__alloc_func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100013d63)
    #7 std::__1::__function::__func<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), std::__1::allocator<itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>, void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x1000128fc)
    #8 std::__1::__function::__value_func<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1000120b6)
    #9 std::__1::function<void (itk::ImageRegion<2u> const&)>::operator()(itk::ImageRegion<2u> const&) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x100011fe8)
    #10 void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)::operator()(long const*, unsigned long const*) const itkMultiThreaderBase.h:350 (ITKLabelMapTestDriver:x86_64+0x100011ed7)
    #11 decltype(std::__1::forward<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&>(fp)(std::__1::forward<long const*>(fp0), std::__1::forward<unsigned long const*>(fp0))) std::__1::__invoke<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x100011dfe)
    #12 void std::__1::__invoke_void_return_wrapper<void>::__call<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&&&, long const*&&, unsigned long const*&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x100011d48)
    #13 std::__1::__function::__alloc_func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1527 (ITKLabelMapTestDriver:x86_64+0x100011c78)
    #14 std::__1::__function::__func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u>(itk::ImageRegion<2u> const&, std::__1::function<void (itk::ImageRegion<2u> const&)>, itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) functional:1651 (ITKLabelMapTestDriver:x86_64+0x100010640)
    #15 std::__1::__function::__value_func<void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) const functional:1799 (ITKLabelMapTestDriver:x86_64+0x10135193a)
    #16 std::__1::function<void (long const*, unsigned long const*)>::operator()(long const*, unsigned long const*) const functional:2347 (ITKLabelMapTestDriver:x86_64+0x101349ec3)
    #17 itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5::operator()() const itkPoolMultiThreader.cxx:271 (ITKLabelMapTestDriver:x86_64+0x1013de1aa)
    #18 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(fp)()) std::__1::__invoke<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de111)
    #19 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&, std::__1::tuple<>&, std::__1::__tuple_indices<>, std::__1::tuple<>&&) functional:2644 (ITKLabelMapTestDriver:x86_64+0x1013de0c9)
    #20 std::__1::__bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5, std::__1::tuple<>, std::__1::tuple<> >::value>::type std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::operator()<>() functional:2677 (ITKLabelMapTestDriver:x86_64+0x1013de089)
    #21 decltype(std::__1::forward<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(fp)()) std::__1::__invoke<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&>(std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>&&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013de021)
    #22 std::__1::__packaged_task_func<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>, std::__1::allocator<std::__1::__bind<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5> >, void* ()>::operator()() future:1821 (ITKLabelMapTestDriver:x86_64+0x1013dd8a5)
    #23 std::__1::__packaged_task_function<void* ()>::operator()() const future:1998 (ITKLabelMapTestDriver:x86_64+0x1013d6cbf)
    #24 std::__1::packaged_task<void* ()>::operator()() future:2089 (ITKLabelMapTestDriver:x86_64+0x1013d6b6e)
    #25 std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()::operator()() const itkThreadPool.h:97 (ITKLabelMapTestDriver:x86_64+0x1013e0091)
    #26 decltype(std::__1::forward<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(fp)()) std::__1::__invoke<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e0021)
    #27 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&&&) __functional_base:349 (ITKLabelMapTestDriver:x86_64+0x1013dffb1)
    #28 std::__1::__function::__alloc_func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1527 (ITKLabelMapTestDriver:x86_64+0x1013dff71)
    #29 std::__1::__function::__func<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::result_of<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5 ()>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void ()>::operator()() functional:1651 (ITKLabelMapTestDriver:x86_64+0x1013de9ed)
    #30 std::__1::__function::__value_func<void ()>::operator()() const functional:1799 (ITKLabelMapTestDriver:x86_64+0x1013a6c84)
    #31 std::__1::function<void ()>::operator()() const functional:2347 (ITKLabelMapTestDriver:x86_64+0x1013a27e9)
    #32 itk::ThreadPool::ThreadExecute() itkThreadPool.cxx:211 (ITKLabelMapTestDriver:x86_64+0x1013e0e5a)
    #33 decltype(std::__1::forward<void (*)()>(fp)()) std::__1::__invoke<void (*)()>(void (*&&)()) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e7f76)
    #34 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>&, std::__1::__tuple_indices<>) thread:342 (ITKLabelMapTestDriver:x86_64+0x1013e7e59)
    #35 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) thread:352 (ITKLabelMapTestDriver:x86_64+0x1013e760a)

  Previous write of size 1 at 0x7bc00005cd56 by thread T8:
    [failed to restore the stack]

  Location is heap block of size 65536 at 0x7bc000050000 allocated by main thread:
    #0 operator new[](unsigned long) <null>:5891680 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x6ed8b)
    #1 itk::ImportImageContainer<unsigned long, unsigned char>::AllocateElements(unsigned long, bool) const itkImportImageContainer.hxx:180 (ITKLabelMapTestDriver:x86_64+0x10001b2da)
    #2 itk::ImportImageContainer<unsigned long, unsigned char>::Reserve(unsigned long, bool) itkImportImageContainer.hxx:85 (ITKLabelMapTestDriver:x86_64+0x10001c3e5)
    #3 itk::Image<unsigned char, 2u>::Allocate(bool) itkImage.hxx:53 (ITKLabelMapTestDriver:x86_64+0x1000186f6)
    #4 itk::ImageSource<itk::Image<unsigned char, 2u> >::AllocateOutputs() itkImageSource.hxx:184 (ITKLabelMapTestDriver:x86_64+0x10000d752)
    #5 itk::ImageSource<itk::Image<unsigned char, 2u> >::GenerateData() itkImageSource.hxx:215 (ITKLabelMapTestDriver:x86_64+0x10000ea7a)
    #6 itk::ProcessObject::UpdateOutputData(itk::DataObject*) itkProcessObject.cxx:1708 (ITKLabelMapTestDriver:x86_64+0x1013344a8)
    #7 itk::DataObject::UpdateOutputData() itkDataObject.cxx:376 (ITKLabelMapTestDriver:x86_64+0x101370a4d)
    #8 itk::ImageBase<2u>::UpdateOutputData() itkImageBase.hxx:263 (ITKLabelMapTestDriver:x86_64+0x10001747a)
    #9 itk::ImageFileWriter<itk::Image<unsigned char, 2u> >::Write() itkImageFileWriter.hxx:284 (ITKLabelMapTestDriver:x86_64+0x1000580ad)
    #10 itk::ImageFileWriter<itk::Image<unsigned char, 2u> >::Update() itkImageFileWriter.h:178 (ITKLabelMapTestDriver:x86_64+0x1000568f5)
    #11 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:136 (ITKLabelMapTestDriver:x86_64+0x100af9088)
    #12 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

  Thread T10 (tid=106450770, running) created by main thread at:
    #0 pthread_create <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x2933d)
    #1 std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:328 (ITKLabelMapTestDriver:x86_64+0x1013e7589)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:368 (ITKLabelMapTestDriver:x86_64+0x1013e73cc)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:360 (ITKLabelMapTestDriver:x86_64+0x1013e7300)
    #4 void std::__1::allocator<std::__1::thread>::construct<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) memory:1826 (ITKLabelMapTestDriver:x86_64+0x1013e72b8)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::__construct<std::__1::thread, void (*)()>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1718 (ITKLabelMapTestDriver:x86_64+0x1013e7268)
    #6 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::construct<std::__1::thread, void (*)()>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1561 (ITKLabelMapTestDriver:x86_64+0x1013e7118)
    #7 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::emplace_back<void (*)()>(void (*&&)()) vector:1688 (ITKLabelMapTestDriver:x86_64+0x1013e0d12)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:x86_64+0x1013e0ac6)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:x86_64+0x1013e0f49)
    #10 itk::ThreadPool::GetInstance()::$_2::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:x86_64+0x1013e620b)
    #11 decltype(std::__1::forward<itk::ThreadPool::GetInstance()::$_2>(fp)()) std::__1::__invoke<itk::ThreadPool::GetInstance()::$_2>(itk::ThreadPool::GetInstance()::$_2&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e6103)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::__execute<>(std::__1::__tuple_indices<>) mutex:622 (ITKLabelMapTestDriver:x86_64+0x1013e60d1)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::operator()() mutex:614 (ITKLabelMapTestDriver:x86_64+0x1013e6079)
    #14 void std::__1::__call_once_proxy<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >(void*) mutex:650 (ITKLabelMapTestDriver:x86_64+0x1013e5f19)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x69a0e)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:x86_64+0x1013e0681)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:x86_64+0x1013ca496)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:x86_64+0x1013ca7b9)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:x86_64+0x1013493c5)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:419 (ITKLabelMapTestDriver:x86_64+0x101348ef0)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:x86_64+0x10132bf1a)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u> >::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:x86_64+0x10000a020)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:x86_64+0x100009ef4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:x86_64+0x100009d19)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:x86_64+0x100008475)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:x86_64+0x100af8800)
    #27 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

  Thread T8 (tid=106450768, running) created by main thread at:
    #0 pthread_create <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x2933d)
    #1 std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:328 (ITKLabelMapTestDriver:x86_64+0x1013e7589)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:368 (ITKLabelMapTestDriver:x86_64+0x1013e73cc)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:360 (ITKLabelMapTestDriver:x86_64+0x1013e7300)
    #4 void std::__1::allocator<std::__1::thread>::construct<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) memory:1826 (ITKLabelMapTestDriver:x86_64+0x1013e72b8)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::__construct<std::__1::thread, void (*)()>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1718 (ITKLabelMapTestDriver:x86_64+0x1013e7268)
    #6 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::construct<std::__1::thread, void (*)()>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) memory:1561 (ITKLabelMapTestDriver:x86_64+0x1013e7118)
    #7 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::emplace_back<void (*)()>(void (*&&)()) vector:1688 (ITKLabelMapTestDriver:x86_64+0x1013e0d12)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:x86_64+0x1013e0ac6)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:x86_64+0x1013e0f49)
    #10 itk::ThreadPool::GetInstance()::$_2::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:x86_64+0x1013e620b)
    #11 decltype(std::__1::forward<itk::ThreadPool::GetInstance()::$_2>(fp)()) std::__1::__invoke<itk::ThreadPool::GetInstance()::$_2>(itk::ThreadPool::GetInstance()::$_2&&) type_traits:4361 (ITKLabelMapTestDriver:x86_64+0x1013e6103)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::__execute<>(std::__1::__tuple_indices<>) mutex:622 (ITKLabelMapTestDriver:x86_64+0x1013e60d1)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >::operator()() mutex:614 (ITKLabelMapTestDriver:x86_64+0x1013e6079)
    #14 void std::__1::__call_once_proxy<std::__1::tuple<itk::ThreadPool::GetInstance()::$_2&&> >(void*) mutex:650 (ITKLabelMapTestDriver:x86_64+0x1013e5f19)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:5891728 (libclang_rt.tsan_osx_dynamic.dylib:x86_64+0x69a0e)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:x86_64+0x1013e0681)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:x86_64+0x1013ca496)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:x86_64+0x1013ca7b9)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:x86_64+0x1013493c5)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:419 (ITKLabelMapTestDriver:x86_64+0x101348ef0)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:x86_64+0x10132bf1a)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u> >::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:x86_64+0x10000a020)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:x86_64+0x100009ef4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:x86_64+0x100009d19)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char> >::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:x86_64+0x100008475)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:x86_64+0x100af8800)
    #27 main ITKLabelMapTestDriver.cxx:513 (ITKLabelMapTestDriver:x86_64+0x100002473)

SUMMARY: ThreadSanitizer: data race itkImage.h:211 in itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&)
==================
Trying writer->Update()
<DartMeasurement name="ImageError cthead1Label-label-statistics-unique-labelmap-baseline1.png" type="numeric/double">14</DartMeasurement>
<DartMeasurement name="ImageError" type="numeric/double">14</DartMeasurement>
<DartMeasurement name="ImageError Minimum" type="numeric/double">82</DartMeasurement>
<DartMeasurement name="ImageError Maximum" type="numeric/double">82</DartMeasurement>
<DartMeasurement name="ImageError Mean" type="numeric/double">82</DartMeasurement>
<DartMeasurementFile name="DifferenceImage" type="image/png">/Users/sean/external/ITK-test-bin/Testing/Temporary/itkStatisticsUniqueLabelMapFilterTest1.png.diff.png</DartMeasurementFile>
<DartMeasurementFile name="BaselineImage" type="image/png">/Users/sean/external/ITK-test-bin/Testing/Temporary/itkStatisticsUniqueLabelMapFilterTest1.png.base.png</DartMeasurementFile>
<DartMeasurementFile name="TestImage" type="image/png">/Users/sean/external/ITK-test-bin/Testing/Temporary/itkStatisticsUniqueLabelMapFilterTest1.png.test.png</DartMeasurementFile>
<DartMeasurement name="BaselineImageName" type="text/string">cthead1Label-label-statistics-unique-labelmap-baseline1.png</DartMeasurement>
<DartMeasurement name="ImageError cthead1Label-label-statistics-unique-labelmap-dilate-baseline1.png" type="numeric/double">0</DartMeasurement>
<DartMeasurement name="BaselineImageName" type="text/string">cthead1Label-label-statistics-unique-labelmap-dilate-baseline1.png</DartMeasurement>
ThreadSanitizer: reported 2 warnings
Abort trap: 6
```

### LINKED ISSUE #4655: thread race with itkImage::SetPixel() found with thread sanitizer (TSan)
Several ITK tests report errors with thread sanitizer.  For several of them, the issue is the same. `itkImage::SetPixel()` is being used by different threads to write to the *same memory location simultaneously*. Even if each thread is writing the same value (I didn't check), this is still undefined behaviour (without an atomic write).

```
  void
  SetPixel(const IndexType & index, const TPixel & value)
  {
    OffsetValueType offset = this->FastComputeOffset(index);
    (*m_Buffer)[offset] = value; // 🔥
  }
```

***If*** each thread is writing the same value, I think this could be fixed, on gcc/clang at least, by using `__atomic_store_n` and `__atomic_load_n` in `GetPixel`/`SetPixel`. I tried, but couldn't figure out all the C++ templates to get down to the raw buffer.

Long term, C++20 `std::atomic_ref` could help too. (It's a wrapper of the aforemenioned compiler intrinsics.)

For example, the test `itkStatisticsUniqueLabelMapFilterTest1` results in the following report:

```
WARNING: ThreadSanitizer: data race (pid=25678)
  Write of size 1 at 0x00010c45cd58 by thread T18:
    #0 itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&) itkImage.h:211 (ITKLabelMapTestDriver:arm64+0x10008cb6c)
    #1 itk::LabelMapToLabelImageFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u>>, itk::Image<unsigned char, 2u>>::ThreadedProcessLabelObject(itk::StatisticsLabelObject<unsigned char, 2u>*) itkLabelMapToLabelImageFilter.hxx:51 (ITKLabelMapTestDriver:arm64+0x10056d54c)
    #2 itk::LabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u>>, itk::Image<unsigned char, 2u>>::DynamicThreadedGenerateData(itk::ImageRegion<2u> const&) itkLabelMapFilter.hxx:113 (ITKLabelMapTestDriver:arm64+0x10056ca7c)
    #3 itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)::operator()(itk::ImageRegion<2u> const&) const itkImageSource.hxx:231 (ITKLabelMapTestDriver:arm64+0x100016fc0)
    #4 void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)::operator()(long const*, unsigned long const*) const itkMultiThreaderBase.h:353 (ITKLabelMapTestDriver:arm64+0x100016e2c)
    #5 decltype(std::declval<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&>()(std::declval<long const*>(), std::declval<unsigned long const*>())) std::__1::__invoke[abi:v160006]<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*&&, unsigned long const*&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x100016cf0)
    #6 void std::__1::__invoke_void_return_wrapper<void, true>::__call<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*&&, unsigned long const*&&) invoke.h:487 (ITKLabelMapTestDriver:arm64+0x100016c04)
    #7 std::__1::__function::__alloc_func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()[abi:v160006](long const*&&, unsigned long const*&&) function.h:185 (ITKLabelMapTestDriver:arm64+0x100016b90)
    #8 std::__1::__function::__func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) function.h:356 (ITKLabelMapTestDriver:arm64+0x100014888)
    #9 std::__1::__function::__value_func<void (long const*, unsigned long const*)>::operator()[abi:v160006](long const*&&, unsigned long const*&&) const function.h:510 (ITKLabelMapTestDriver:arm64+0x10169cebc)
    #10 std::__1::function<void (long const*, unsigned long const*)>::operator()(long const*, unsigned long const*) const function.h:1156 (ITKLabelMapTestDriver:arm64+0x101697f74)
    #11 itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5::operator()() const itkPoolMultiThreader.cxx:271 (ITKLabelMapTestDriver:arm64+0x10171f118)
    #12 std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()::operator()() const itkThreadPool.h:92 (ITKLabelMapTestDriver:arm64+0x10171f06c)
    #13 decltype(std::declval<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>()()) std::__1::__invoke[abi:v160006]<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x10171f010)
    #14 std::__1::__packaged_task_func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void* ()>::operator()() future:1694 (ITKLabelMapTestDriver:arm64+0x10171e750)
    #15 std::__1::__packaged_task_function<void* ()>::operator()() const future:1880 (ITKLabelMapTestDriver:arm64+0x101715640)
    #16 std::__1::packaged_task<void* ()>::operator()() future:1957 (ITKLabelMapTestDriver:arm64+0x101715458)
    #17 std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()::operator()() const itkThreadPool.h:97 (ITKLabelMapTestDriver:arm64+0x1017225a8)
    #18 decltype(std::declval<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>()()) std::__1::__invoke[abi:v160006]<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x101722550)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&>(std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&) invoke.h:487 (ITKLabelMapTestDriver:arm64+0x1017224b4)
    #20 std::__1::__function::__alloc_func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()>, void ()>::operator()[abi:v160006]() function.h:185 (ITKLabelMapTestDriver:arm64+0x101722460)
    #21 std::__1::__function::__func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()>, void ()>::operator()() function.h:356 (ITKLabelMapTestDriver:arm64+0x1017200c4)
    #22 std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const function.h:510 (ITKLabelMapTestDriver:arm64+0x1016e3a54)
    #23 std::__1::function<void ()>::operator()() const function.h:1156 (ITKLabelMapTestDriver:arm64+0x1016df260)
    #24 itk::ThreadPool::ThreadExecute() itkThreadPool.cxx:211 (ITKLabelMapTestDriver:arm64+0x1017238c8)
    #25 decltype(std::declval<void (*)()>()()) std::__1::__invoke[abi:v160006]<void (*)()>(void (*&&)()) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x10172cf90)
    #26 void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>&, std::__1::__tuple_indices<>) thread:288 (ITKLabelMapTestDriver:arm64+0x10172ceac)
    #27 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>>(void*) thread:299 (ITKLabelMapTestDriver:arm64+0x10172c240)

  Previous write of size 1 at 0x00010c45cd58 by thread T6:
    #0 itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&) itkImage.h:211 (ITKLabelMapTestDriver:arm64+0x10008cb6c)
    #1 itk::LabelMapToLabelImageFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u>>, itk::Image<unsigned char, 2u>>::ThreadedProcessLabelObject(itk::StatisticsLabelObject<unsigned char, 2u>*) itkLabelMapToLabelImageFilter.hxx:51 (ITKLabelMapTestDriver:arm64+0x10056d54c)
    #2 itk::LabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u>>, itk::Image<unsigned char, 2u>>::DynamicThreadedGenerateData(itk::ImageRegion<2u> const&) itkLabelMapFilter.hxx:113 (ITKLabelMapTestDriver:arm64+0x10056ca7c)
    #3 itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)::operator()(itk::ImageRegion<2u> const&) const itkImageSource.hxx:231 (ITKLabelMapTestDriver:arm64+0x100016fc0)
    #4 void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)::operator()(long const*, unsigned long const*) const itkMultiThreaderBase.h:353 (ITKLabelMapTestDriver:arm64+0x100016e2c)
    #5 decltype(std::declval<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&>()(std::declval<long const*>(), std::declval<unsigned long const*>())) std::__1::__invoke[abi:v160006]<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*&&, unsigned long const*&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x100016cf0)
    #6 void std::__1::__invoke_void_return_wrapper<void, true>::__call<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*, unsigned long const*>(void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)&, long const*&&, unsigned long const*&&) invoke.h:487 (ITKLabelMapTestDriver:arm64+0x100016c04)
    #7 std::__1::__function::__alloc_func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()[abi:v160006](long const*&&, unsigned long const*&&) function.h:185 (ITKLabelMapTestDriver:arm64+0x100016b90)
    #8 std::__1::__function::__func<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*), std::__1::allocator<void itk::MultiThreaderBase::ParallelizeImageRegion<2u, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&)>(itk::ImageRegion<2u> const&, itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData()::'lambda'(itk::ImageRegion<2u> const&), itk::ProcessObject*)::'lambda'(long const*, unsigned long const*)>, void (long const*, unsigned long const*)>::operator()(long const*&&, unsigned long const*&&) function.h:356 (ITKLabelMapTestDriver:arm64+0x100014888)
    #9 std::__1::__function::__value_func<void (long const*, unsigned long const*)>::operator()[abi:v160006](long const*&&, unsigned long const*&&) const function.h:510 (ITKLabelMapTestDriver:arm64+0x10169cebc)
    #10 std::__1::function<void (long const*, unsigned long const*)>::operator()(long const*, unsigned long const*) const function.h:1156 (ITKLabelMapTestDriver:arm64+0x101697f74)
    #11 itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5::operator()() const itkPoolMultiThreader.cxx:271 (ITKLabelMapTestDriver:arm64+0x10171f118)
    #12 std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()::operator()() const itkThreadPool.h:92 (ITKLabelMapTestDriver:arm64+0x10171f06c)
    #13 decltype(std::declval<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>()()) std::__1::__invoke[abi:v160006]<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x10171f010)
    #14 std::__1::__packaged_task_func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda'()>, void* ()>::operator()() future:1694 (ITKLabelMapTestDriver:arm64+0x10171e750)
    #15 std::__1::__packaged_task_function<void* ()>::operator()() const future:1880 (ITKLabelMapTestDriver:arm64+0x101715640)
    #16 std::__1::packaged_task<void* ()>::operator()() future:1957 (ITKLabelMapTestDriver:arm64+0x101715458)
    #17 std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()::operator()() const itkThreadPool.h:97 (ITKLabelMapTestDriver:arm64+0x1017225a8)
    #18 decltype(std::declval<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>()()) std::__1::__invoke[abi:v160006]<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x101722550)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&>(std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()&) invoke.h:487 (ITKLabelMapTestDriver:arm64+0x1017224b4)
    #20 std::__1::__function::__alloc_func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()>, void ()>::operator()[abi:v160006]() function.h:185 (ITKLabelMapTestDriver:arm64+0x101722460)
    #21 std::__1::__function::__func<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'(), std::__1::allocator<std::__1::future<std::__1::invoke_result<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>::type> itk::ThreadPool::AddWork<itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5>(itk::PoolMultiThreader::ParallelizeImageRegion(unsigned int, long const*, unsigned long const*, std::__1::function<void (long const*, unsigned long const*)>, itk::ProcessObject*)::$_5&&)::'lambda0'()>, void ()>::operator()() function.h:356 (ITKLabelMapTestDriver:arm64+0x1017200c4)
    #22 std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const function.h:510 (ITKLabelMapTestDriver:arm64+0x1016e3a54)
    #23 std::__1::function<void ()>::operator()() const function.h:1156 (ITKLabelMapTestDriver:arm64+0x1016df260)
    #24 itk::ThreadPool::ThreadExecute() itkThreadPool.cxx:211 (ITKLabelMapTestDriver:arm64+0x1017238c8)
    #25 decltype(std::declval<void (*)()>()()) std::__1::__invoke[abi:v160006]<void (*)()>(void (*&&)()) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x10172cf90)
    #26 void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>&, std::__1::__tuple_indices<>) thread:288 (ITKLabelMapTestDriver:arm64+0x10172ceac)
    #27 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>>(void*) thread:299 (ITKLabelMapTestDriver:arm64+0x10172c240)

  Location is heap block of size 65536 at 0x00010c450000 allocated by main thread:
    #0 operator new[](unsigned long) <null>:83005060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x8451c)
    #1 itk::ImportImageContainer<unsigned long, unsigned char>::AllocateElements(unsigned long, bool) const itkImportImageContainer.hxx:168 (ITKLabelMapTestDriver:arm64+0x100022ae0)
    #2 itk::ImportImageContainer<unsigned long, unsigned char>::Reserve(unsigned long, bool) itkImportImageContainer.hxx:76 (ITKLabelMapTestDriver:arm64+0x100025e58)
    #3 itk::Image<unsigned char, 2u>::Allocate(bool) itkImage.hxx:46 (ITKLabelMapTestDriver:arm64+0x10001e49c)
    #4 itk::ImageSource<itk::Image<unsigned char, 2u>>::AllocateOutputs() itkImageSource.hxx:184 (ITKLabelMapTestDriver:arm64+0x100010904)
    #5 itk::ImageSource<itk::Image<unsigned char, 2u>>::GenerateData() itkImageSource.hxx:213 (ITKLabelMapTestDriver:arm64+0x1000124e4)
    #6 itk::ProcessObject::UpdateOutputData(itk::DataObject*) itkProcessObject.cxx:1694 (ITKLabelMapTestDriver:arm64+0x10167ffe0)
    #7 itk::DataObject::UpdateOutputData() itkDataObject.cxx:388 (ITKLabelMapTestDriver:arm64+0x1016be2a8)
    #8 itk::ImageBase<2u>::UpdateOutputData() itkImageBase.hxx:265 (ITKLabelMapTestDriver:arm64+0x10001c9c4)
    #9 itk::ImageFileWriter<itk::Image<unsigned char, 2u>>::Write() itkImageFileWriter.hxx:285 (ITKLabelMapTestDriver:arm64+0x1000906d0)
    #10 itk::ImageFileWriter<itk::Image<unsigned char, 2u>>::Write() itkImageFileWriter.hxx:81 (ITKLabelMapTestDriver:arm64+0x10008ea30)
    #11 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:136 (ITKLabelMapTestDriver:arm64+0x100938200)
    #12 main ITKLabelMapTestDriver.cxx:523 (ITKLabelMapTestDriver:arm64+0x1000053e4)

  Thread T18 (tid=60135496, running) created by main thread at:
    #0 pthread_create <null>:83005060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x3062c)
    #1 std::__1::__libcpp_thread_create[abi:v160006](_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:378 (ITKLabelMapTestDriver:arm64+0x10172c1a8)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:315 (ITKLabelMapTestDriver:arm64+0x10172bf4c)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:307 (ITKLabelMapTestDriver:arm64+0x10172be74)
    #4 void std::__1::allocator<std::__1::thread>::construct[abi:v160006]<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) allocator.h:168 (ITKLabelMapTestDriver:arm64+0x10172be0c)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread>>::construct[abi:v160006]<std::__1::thread, void (*)(), void>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) allocator_traits.h:296 (ITKLabelMapTestDriver:arm64+0x10172bc68)
    #6 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread>>::__construct_one_at_end[abi:v160006]<void (*)()>(void (*&&)()) vector:811 (ITKLabelMapTestDriver:arm64+0x10172b9b4)
    #7 std::__1::thread& std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread>>::emplace_back<void (*)()>(void (*&&)()) vector:1600 (ITKLabelMapTestDriver:arm64+0x101723720)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:arm64+0x101723380)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:arm64+0x101723a10)
    #10 itk::ThreadPool::GetInstance()::$_1::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:arm64+0x101728e5c)
    #11 decltype(std::declval<itk::ThreadPool::GetInstance()::$_1>()()) std::__1::__invoke[abi:v160006]<itk::ThreadPool::GetInstance()::$_1>(itk::ThreadPool::GetInstance()::$_1&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x101728d4c)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>::__execute[abi:v160006]<>(std::__1::__tuple_indices<>) mutex:624 (ITKLabelMapTestDriver:arm64+0x101728cf8)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>::operator()[abi:v160006]() mutex:616 (ITKLabelMapTestDriver:arm64+0x101728c90)
    #14 void std::__1::__call_once_proxy[abi:v160006]<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>(void*) mutex:652 (ITKLabelMapTestDriver:arm64+0x101728a64)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:83005060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7e250)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:arm64+0x101722e20)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:arm64+0x10170683c)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:arm64+0x101706d04)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:arm64+0x101696cf4)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:389 (ITKLabelMapTestDriver:arm64+0x1016965dc)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:arm64+0x101674a54)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u>>::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:arm64+0x10000b8c4)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:arm64+0x10000b6d4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:arm64+0x10000b394)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:arm64+0x10000a400)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:arm64+0x1009375d8)
    #27 main ITKLabelMapTestDriver.cxx:523 (ITKLabelMapTestDriver:arm64+0x1000053e4)

  Thread T6 (tid=60135484, running) created by main thread at:
    #0 pthread_create <null>:83005060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x3062c)
    #1 std::__1::__libcpp_thread_create[abi:v160006](_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:378 (ITKLabelMapTestDriver:arm64+0x10172c1a8)
    #2 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:315 (ITKLabelMapTestDriver:arm64+0x10172bf4c)
    #3 std::__1::thread::thread<void (*)(), void>(void (*&&)()) thread:307 (ITKLabelMapTestDriver:arm64+0x10172be74)
    #4 void std::__1::allocator<std::__1::thread>::construct[abi:v160006]<std::__1::thread, void (*)()>(std::__1::thread*, void (*&&)()) allocator.h:168 (ITKLabelMapTestDriver:arm64+0x10172be0c)
    #5 void std::__1::allocator_traits<std::__1::allocator<std::__1::thread>>::construct[abi:v160006]<std::__1::thread, void (*)(), void>(std::__1::allocator<std::__1::thread>&, std::__1::thread*, void (*&&)()) allocator_traits.h:296 (ITKLabelMapTestDriver:arm64+0x10172bc68)
    #6 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread>>::__construct_one_at_end[abi:v160006]<void (*)()>(void (*&&)()) vector:811 (ITKLabelMapTestDriver:arm64+0x10172b9b4)
    #7 std::__1::thread& std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread>>::emplace_back<void (*)()>(void (*&&)()) vector:1600 (ITKLabelMapTestDriver:arm64+0x101723720)
    #8 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:118 (ITKLabelMapTestDriver:arm64+0x101723380)
    #9 itk::ThreadPool::ThreadPool() itkThreadPool.cxx:108 (ITKLabelMapTestDriver:arm64+0x101723a10)
    #10 itk::ThreadPool::GetInstance()::$_1::operator()() const itkThreadPool.cxx:83 (ITKLabelMapTestDriver:arm64+0x101728e5c)
    #11 decltype(std::declval<itk::ThreadPool::GetInstance()::$_1>()()) std::__1::__invoke[abi:v160006]<itk::ThreadPool::GetInstance()::$_1>(itk::ThreadPool::GetInstance()::$_1&&) invoke.h:394 (ITKLabelMapTestDriver:arm64+0x101728d4c)
    #12 void std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>::__execute[abi:v160006]<>(std::__1::__tuple_indices<>) mutex:624 (ITKLabelMapTestDriver:arm64+0x101728cf8)
    #13 std::__1::__call_once_param<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>::operator()[abi:v160006]() mutex:616 (ITKLabelMapTestDriver:arm64+0x101728c90)
    #14 void std::__1::__call_once_proxy[abi:v160006]<std::__1::tuple<itk::ThreadPool::GetInstance()::$_1&&>>(void*) mutex:652 (ITKLabelMapTestDriver:arm64+0x101728a64)
    #15 __tsan::(anonymous namespace)::call_once_callback_wrapper(void*) <null>:83005060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7e250)
    #16 itk::ThreadPool::GetInstance() itkThreadPool.cxx:79 (ITKLabelMapTestDriver:arm64+0x101722e20)
    #17 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:81 (ITKLabelMapTestDriver:arm64+0x10170683c)
    #18 itk::PoolMultiThreader::PoolMultiThreader() itkPoolMultiThreader.cxx:82 (ITKLabelMapTestDriver:arm64+0x101706d04)
    #19 itk::PoolMultiThreader::New() itkPoolMultiThreader.h:57 (ITKLabelMapTestDriver:arm64+0x101696cf4)
    #20 itk::MultiThreaderBase::New() itkMultiThreaderBase.cxx:389 (ITKLabelMapTestDriver:arm64+0x1016965dc)
    #21 itk::ProcessObject::ProcessObject() itkProcessObject.cxx:72 (ITKLabelMapTestDriver:arm64+0x101674a54)
    #22 itk::ImageSource<itk::Image<unsigned char, 2u>>::ImageSource() itkImageSource.h:230 (ITKLabelMapTestDriver:arm64+0x10000b8c4)
    #23 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::ImageFileReader() itkImageFileReader.h:122 (ITKLabelMapTestDriver:arm64+0x10000b6d4)
    #24 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::ImageFileReader() itkImageFileReader.hxx:36 (ITKLabelMapTestDriver:arm64+0x10000b394)
    #25 itk::ImageFileReader<itk::Image<unsigned char, 2u>, itk::DefaultConvertPixelTraits<unsigned char>>::New() itkImageFileReader.h:86 (ITKLabelMapTestDriver:arm64+0x10000a400)
    #26 itkStatisticsUniqueLabelMapFilterTest1(int, char**) itkStatisticsUniqueLabelMapFilterTest1.cxx:62 (ITKLabelMapTestDriver:arm64+0x1009375d8)
    #27 main ITKLabelMapTestDriver.cxx:523 (ITKLabelMapTestDriver:arm64+0x1000053e4)

SUMMARY: ThreadSanitizer: data race itkImage.h:211 in itk::Image<unsigned char, 2u>::SetPixel(itk::Index<2u> const&, unsigned char const&)
==================
```

### PR DESCRIPTION
**Pull request by blowekamp**
Address bugs in unique label map filters
Two bugs were addressed which could cause overlapping and/or errouneous
outputs.

1. When a line we trimmed in the front, it is not placed back into the
queue to ensure that it is still the first one, and the asserted
assumptions of the order remain true.
2. Fix comparisons between start and ends to be correct for an
interval of pixels where the start+length is not included.

closes #4655 
closes #3031

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
@blowekamp are you set up to use TSan, or do you want me to try with patch with TSan?

**Comment by dzenanz** [comment]
I believe this does not patch it, it just explicitly checks for label overlaps.

**Comment by blowekamp** [comment]
I think this is pretty close to fixing the issue, more testing is needed.

**Review by dzenanz — COMMENTED** [review]
In the commit message, `label map filers` -> `label map filters`. The rest looks good on a glance.

File: Modules/Filtering/LabelMap/include/itkShapeUniqueLabelMapFilter.h [hunk 1]
```diff
@@ -177,6 +177,8 @@ class ITK_TEMPLATE_EXPORT ShapeUniqueLabelMapFilter : public InPlaceLabelMapFilt
         }
       }
 
+      assert(newMainLine || (!newMainLine && idx[0] >= prevIdx[0]));
```
Comment (seanm) [inline Modules/Filtering/LabelMap/include/itkShapeUniqueLabelMapFilter.h:180]: the `!newMainLine` is redundant; since it's in the `or` it must be so.

**Comment by blowekamp** [comment]
@seanm You can run the sanitizer. However I was able to detect the bug with additional checks before the threading issue occurs.

**Comment by seanm** [comment]
I'm getting a build error:

```
/Users/sean/external/ITK/Modules/Filtering/LabelMap/test/itkStatisticsUniqueLabelMapFilterTest1.cxx:46:7: error: use of undeclared identifier 'TEST_EXPECT_TRUE'
/Users/sean/external/ITK/Modules/Filtering/LabelMap/test/itkStatisticsUniqueLabelMapFilterTest1.cxx:158:18: note: in instantiation of function template specialization 'CheckLabelMapOverlap<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2>>>' requested here
  int exitCode = CheckLabelMapOverlap(unique->GetOutput());
                 ^
```

and

```
/Users/sean/external/ITK/Modules/Filtering/LabelMap/test/itkStatisticsUniqueLabelMapFilterTest1.cxx:46:7: error: attempt to use a poisoned identifier
      TEST_EXPECT_TRUE(line.GetLength() <= labelObject->GetNumberOfPixels());
      ^
```

**Comment by blowekamp** [comment]
@seanm Thanks looks like that should have been ITK_TEST_EXPECT_TRUE. I am surprised that did not produce a warning on any of the builds.

**Review by thewtex — APPROVED** [review]
Great to have these addressed! 🥇

**Review by seanm — APPROVED** [review]
This solves the itkStatisticsUniqueLabelMapFilterTest1 test failure under TSan! Amazing! We'll see on cdash if it solves other similar failures too...

**Comment by seanm** [comment]
So this is mergeable now?

**Comment by blowekamp** [comment]
@thewtex  I was hoping to get this in for 5.4 but missed it. The current target branch is [release-5.4](https://github.com/InsightSoftwareConsortium/ITK/tree/release-5.4). What should be do to merge this patch?

**Comment by thewtex** [comment]
> @thewtex I was hoping to get this in for 5.4 but missed it. The current target branch is release-5.4. What should be do to merge this patch?

@blowekamp outstanding!

I will go ahead and merge this one. For future reference, the process is:

1. merge topic branch into `release-5.4` via GitHub Web UI
2. merge `release-5.4` into `release` locally (`git checkout release-5.4; git pull --ff-only upstream release-5.4; git checkout release; git pull --ff-only upstream release; git merge release-5.4`)
3. merge `release` into `master` locally (`git checkout master; git pull --ff-only upstream master; git merge release`)
4. locally `git push upstream release master`

**Comment by seanm** [comment]
Cool, I'm excited to see on tomorrow's TSan cdash is this fixes any other tests too:

https://open.cdash.org/builds/9649990

**Comment by seanm** [comment]
Seems it fixed `itkStatisticsUniqueLabelMapFilterTest2`, but not any other test.

**Comment by blowekamp** [comment]
> Seems it fixed `itkStatisticsUniqueLabelMapFilterTest2`, but not any other test.

Are any of the other failure related to label maps?

**Comment by seanm** [comment]
> Are any of the other failure related to label maps?

I haven't analyzed each in depth, but here's the list:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=9652708
