### PR TITLE
ENH: Add a 3D regression test for FillholeImageFilter

### LINKED ISSUE #4326: Fillhole image filter broken in Python for 3D images
On the test 3D image, BinaryFillholeImageFilter in SimpleFilters in 3D Slicer produces reasonable looking output, while ITK-Python output the same thing as input.

### Steps to Reproduce

```py
import itk
import numpy as np

# The existing C++ regression test
mask = itk.imread(r"C:\Dev\ITK-py11\ExternalData\Testing\Data\Input\Spots.png")
mask_filled = itk.binary_fillhole_image_filter(mask, fully_connected=True)
gt = itk.imread(r"C:\Dev\ITK-py11\ExternalData\Modules\Filtering\LabelMap\test\Baseline\itkBinaryFillholeImageFilterTest1.png")
assert np.array_equal(mask_filled, gt)

# new test
im3 = itk.imread(r"C:\Dev\ITK-git\Modules\Filtering\LabelMap\test\Input\fillhole_test_3D.nrrd")
result = itk.binary_fillhole_image_filter(im3, fully_connected=False)
im3f = itk.imread(r"C:\Dev\ITK-git\Modules\Filtering\LabelMap\test\Baseline\fillhole_test_3D_0.nrrd")
assert np.array_equal(result, im3f)  # fails
```

### Expected behavior

ITK Python and Slicer produce the same output.

### Actual behavior

ITK Python filter invocation looks like a no-op.

### Reproducibility

100%

### Versions

```log
C:\Dev\ITK-git\Modules\Filtering\LabelMap\wrapping\test>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import itk
>>> itk.__version__
'5.3.0'
>>> itk.__file__
'C:\\Users\\Dzenan\\AppData\\Roaming\\Python\\Python39\\site-packages\\itk\\__init__.py'
>>> ^Z


C:\Dev\ITK-git\Modules\Filtering\LabelMap\wrapping\test>pip show itk
Name: itk
Version: 5.3.0
```

### Environment

Windows 11 (up-to-date)

### Additional Information

Test images:
[test.zip](https://github.com/InsightSoftwareConsortium/ITK/files/13341110/test.zip)

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #4326.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)

### CODE REVIEW

**Comment by dzenanz** [comment]
Unfortunately, these tests do not reproduce the problem from #4326.

**Comment by dzenanz** [comment]
This force push is a plain rebase.

**Comment by dzenanz** [comment]
I must have done something wrong in the data upload, as the downloaded files are html pages instead of images:
fillhole
I plan to look into it.

File: Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx [hunk 1]
```diff
@@ -76,3 +67,34 @@ itkBinaryFillholeImageFilterTest1(int argc, char * argv[])
...
+{
+  if (argc != 5)
+  {
+    std::cerr << "Missing Parameters." << std::endl;
+    std::cerr << "Usage: " << itkNameOfTestExecutableMacro(argv)
+              << " inputFileName outputFileName fullyConnected foregroundValue" << std::endl;
+    return EXIT_FAILURE;
+  }
+
+  using ImageType = itk::Image<short, 2>;
```
Comment (jhlegarreta) [inline Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx:83]: Not sure why the dimensionality is hard-coded here if the purpose is to test this with 3D data. Maybe it should be provided as an input argument to the test?

Comment (dzenanz) [reply Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx:83]: This image type is only used to instantiate the reader which will determine the on-disk dimension. The `DoIt` has the correct dimension.

Comment (jhlegarreta) [reply Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx:83]: Maybe it is too long since I have not actually read our docs or actively developed, but not sure if I understand: then why is the reader templated? Why don't we put the dimension to e.g. 1 always, regardless of the dimensionality of the image?

Comment (jhlegarreta) [reply Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx:83]: > Removing the explicit dimension specification might be better?

If it does not have a function, then to me it does not help to have the dimension specification in any ways.

I will need to revise my knowledge about the toolkit if it does not have a function; I cannot review the PR.

Comment (dzenanz) [reply Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx]: This approach is inspired by: https://github.com/Slicer/Slicer/blob/5e45824d5cc654a8277205921fb4a1ed129167bb/Base/CLI/itkPluginUtilities.h#L17-L30

Comment (blowekamp) [reply Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx]: The way I sometimes get the dimension of a file is just with the ImageIOBase:
https://github.com/SimpleITK/SimpleITK/blob/46bf97cf954646e284a8ebbc6863ac8b2c5465fe/Code/IO/src/sitkImageReaderBase.cxx#L225

**Review by blowekamp — APPROVED** [review]
Thanks for adding more testing.
