### PR TITLE
BUG: Fix printing of values in MetaDataObject

### LINKED ISSUE #1454: MetaDataDictionary::Print only prints [UNKNOWN_PRINT_CHARACTERISTICS]
### Description

For any MetaDataObject calling `obj->Print(std::cout)` produces "[UNKNOWN_PRINT_CHARACTERISTICS]" on the console. 

https://github.com/InsightSoftwareConsortium/ITK/blob/60469760ee13f48b265ca7424e3e9fd652672710/Modules/Core/Common/include/itkMetaDataObject.hxx#L63-L69

### Expected behavior

For `itk::Object` base objects the `Print` method should be used while those which support `operator<<`, that method should be used.

It is expected to be able to iterate over the metadata dictionary and print the key and value of all types and get descriptive output.

### PR DESCRIPTION
**Pull request by blowekamp**
Also removes dead code related to METADATAPRINT

Does not currently add printing for std::vector.

Fix #1454
Near duplicate of: #4368
Co-Author: Pablo Hernandez-Cerdan <pablo.hernandez.cerdan@outlook.com>

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Code looks elegant. Hopefully it works!

**Comment by blowekamp** [comment]
This also does not make use of itk::Matrix::PrintSelf. The LightObject class provides a standard Print, and PrintSelf method ( with indent). The MetaDataObject class is derived from the LightObject, while the MetaDataDictionary is not.

**Comment by dzenanz** [comment]
Do the image directions and other matrices get printed correctly or as `[UNKNOWN PRINT CHARACTERISTICS]`?

**Comment by blowekamp** [comment]
The itk::Matrix and itk::Array classes get printed with their "operator<<". The new Matrix::PrintSelf (#4772) is not used.

std::vector still get printed with `[UNKNOWN PRINT CHARACTERISTICS]`

**Comment by phcerdan** [comment]
Looks good and thanks for the follow up.
Why aren't we adding support for std::vector or other iterables?
Seems like a good opportunity.

**Review by phcerdan — APPROVED** [review]
Looks good!
In the future, we could look up on how to print iterables in a general way.

**Comment by dzenanz** [comment]
Could [this operator](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.4.0/Modules/Core/Common/include/itkPrintHelper.h#L44) be used?

**Comment by blowekamp** [comment]
> Could [this operator](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.4.0/Modules/Core/Common/include/itkPrintHelper.h#L44) be used?

I ran into issue with the two approaches I tried to use that overloaded operator. Perhaps this can be a second PR?

File: Modules/Core/Common/include/itkMetaDataObject.hxx [hunk 1]
```diff
@@ -59,11 +59,45 @@ MetaDataObject<MetaDataObjectType>::SetMetaDataObjectValue(const MetaDataObjectT
   Self::Assign(m_MetaDataObjectValue, newValue);
 }
 
+namespace
+{
```
Comment (N-Dekker) [inline Modules/Core/Common/include/itkMetaDataObject.hxx:63]: Please don't open an unnamed namespace in a header file (*.h, *.hxx)

Comment (dzenanz) [reply Modules/Core/Common/include/itkMetaDataObject.hxx:63]: Looks like a good excuse for an immediate follow-up? 😄 Is there also some chance for you tackle `std::vector` printing?

Comment (blowekamp) [reply Modules/Core/Common/include/itkMetaDataObject.hxx:63]: @N-Dekker What is the alternative suggestion?  Should move the classes to ITK's meta programming sub namespace?

Comment (N-Dekker) [reply Modules/Core/Common/include/itkMetaDataObject.hxx:63]: > Should move the classes to ITK's meta programming sub namespace?

Good question... is the intention to have `has_Print` and `has_output_operator` as part of the public interface, for end-users? Then they could go into the meta programming sub-namespace. Or they could just remain in the root of the `itk` namespace. But then they should still be moved from the ".hxx" file into a ".h" file

Otherwise, is the intention to make clear to users that `has_Print` and `has_output_operator` are just implementation details? Then we could place them into some implementation-detail-namespace. We could for example name "itkMetaDataObjectImplementationDetail"

A third option: If you want to entirely hide them away from the end-users, you could probably make them privately nested types of MetaDataObject.
