### PR TITLE
BUG: Explicitly initialize CovariantVector in VectorImageTest

### LINKED ISSUE #1247: Valgrind defects in itkVectorImageTest
There are valgrind uninitialized memory conditions detected in the i[tkVectorImageTest](https://open.cdash.org/viewDynamicAnalysisFile.php?id=6595308). The defect looks like:
```
UMC ==35187== Conditional jump or move depends on uninitialised value(s)
==35187==    at 0x15C0A5: bool testVectorImageAdaptor, 6u>(itk::VectorImageToImageAdaptor::Pointer&, itk::VectorImage::Pointer const&, itk::VectorImage::RegionType const&, unsigned int) (itkVectorImageTest.cxx:92)
==35187==    by 0x152187: itkVectorImageTest(int, char**) (itkVectorImageTest.cxx:453)
==35187==    by 0x137314: main (ITKImageAdaptorsTestDriver.cxx:156)
==35187== 
UMC ==35187== Conditional jump or move depends on uninitialised value(s)
==35187==    at 0x15C0DE: bool testVectorImageAdaptor, 6u>(itk::VectorImageToImageAdaptor::Pointer&, itk::VectorImage::Pointer const&, itk::VectorImage::RegionType const&, unsigned int) (itkVectorImageTest.cxx:92)
==35187==    by 0x152187: itkVectorImageTest(int, char**) (itkVectorImageTest.cxx:453)
==35187==    by 0x137314: main (ITKImageAdaptorsTestDriver.cxx:156)
==35187== 
UMC ==35187== Conditional jump or move depends on uninitialised value(s)
==35187==    at 0x15C26A: bool testVectorImageAdaptor, 6u>(itk::VectorImageToImageAdaptor::Pointer&, itk::VectorImage::Pointer const&, itk::VectorImage::RegionType const&, unsigned int) (itkVectorImageTest.cxx:107)
==35187==    by 0x152187: itkVectorImageTest(int, char**) (itkVectorImageTest.cxx:453)
==35187==    by 0x137314: main (ITKImageAdaptorsTestDriver.cxx:156)
==35187== 
UMC ==35187== Conditional jump or move depends on uninitialised value(s)
==35187==    at 0x15C2A3: bool testVectorImageAdaptor, 6u>(itk::VectorImageToImageAdaptor::Pointer&, itk::VectorImage::Pointer const&, itk::VectorImage::RegionType const&, unsigned int) (itkVectorImageTest.cxx:107)
==35187==    by 0x152187: itkVectorImageTest(int, char**) (itkVectorImageTest.cxx:453)
==35187==    by 0x137314: main (ITKImageAdaptorsTestDriver.cxx:156)
==35187== 
```

### PR DESCRIPTION
**Pull request by blowekamp**
Addressing uninitialized value detected by Valgrind.

Closes #1247.

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
Last Valgrind defects! 💚

File: Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx [hunk 1]
```diff
@@ -85,6 +85,7 @@ testVectorImageAdaptor(typename TAdaptor::Pointer &
   {
     using CovariantVectorType = itk::CovariantVector<double, VDimension>;
     CovariantVectorType input;
+    input.Fill(0);
```
Comment (N-Dekker) [inline Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx]: `input.Fill(0)` is fine, although it could also be achieved by C++11 empty initialization-list: `CovariantVectorType input{}`.

Comment (blowekamp) [reply Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx]: I can't grok through all the constructors and C++ POD/aggregate initialization rules to know how to construct all the different array-like ITK class.

Hrmm... The class is not POD, and it has private data so it's not aggregate initialization. `{}` can't be calling the default constructor, because that should have been called with the prior syntax...I really don't know what `{}` is calling, or why.

Comment (N-Dekker) [reply Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx]: In general, I think a default-constructible class `T` should be designed in such a way that a variable `var1` is properly initialized by:

    T var1{};  // Should be properly initialized.

That also works well when `T = int`, it's a fundamental part of C++11 _uniform initialization_.

Whether or not a variable `var2` is properly initialized without the empty initializer-list depends on the type `T`, of course.

    T var2;  // May not be initialized.

My 2 cents

Comment (blowekamp) [reply Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx]: I used `{0.0}` for the initialization to make it explicit its value is zero.

@N-Dekker It was mistaken, the `CovariantVector` is POD as checked by this [nice test](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/test/itkCommonTypeTraitsGTest.cxx#L52). I know understand what is going on with the constructors and the syntax.
